import { db } from "./db";
import { contentTopics, questions } from "@shared/schema";

async function seed() {
  console.log("Starting database seed...");

  // Create topics for Physics
  const physicsTopics = await db.insert(contentTopics).values([
    {
      subject: "Physics",
      classLevel: "Class 11",
      topicName: "Kinematics",
      ncertChapter: "Chapter 3: Motion in a Straight Line",
      referenceBooks: ["HC Verma - Concepts of Physics Part 1"],
    },
    {
      subject: "Physics",
      classLevel: "Class 11",
      topicName: "Laws of Motion",
      ncertChapter: "Chapter 5: Laws of Motion",
      referenceBooks: ["HC Verma - Concepts of Physics Part 1"],
    },
    {
      subject: "Physics",
      classLevel: "Class 12",
      topicName: "Electrostatics",
      ncertChapter: "Chapter 1: Electric Charges and Fields",
      referenceBooks: ["HC Verma - Concepts of Physics Part 2"],
    },
  ]).returning();

  // Create topics for Chemistry
  const chemistryTopics = await db.insert(contentTopics).values([
    {
      subject: "Chemistry",
      classLevel: "Class 11",
      topicName: "Atomic Structure",
      ncertChapter: "Chapter 2: Structure of Atom",
      referenceBooks: ["Physical Chemistry - P. Bahadur"],
    },
    {
      subject: "Chemistry",
      classLevel: "Class 11",
      topicName: "Chemical Bonding",
      ncertChapter: "Chapter 4: Chemical Bonding and Molecular Structure",
      referenceBooks: ["Physical Chemistry - P. Bahadur"],
    },
    {
      subject: "Chemistry",
      classLevel: "Class 12",
      topicName: "Electrochemistry",
      ncertChapter: "Chapter 3: Electrochemistry",
      referenceBooks: ["Physical Chemistry - P. Bahadur"],
    },
  ]).returning();

  // Create topics for Botany
  const botanyTopics = await db.insert(contentTopics).values([
    {
      subject: "Botany",
      classLevel: "Class 11",
      topicName: "Cell Structure and Function",
      ncertChapter: "Chapter 8: Cell - The Unit of Life",
      referenceBooks: ["Trueman's Biology Class 11"],
    },
    {
      subject: "Botany",
      classLevel: "Class 11",
      topicName: "Plant Physiology",
      ncertChapter: "Chapter 13: Photosynthesis in Higher Plants",
      referenceBooks: ["Trueman's Biology Class 11"],
    },
    {
      subject: "Botany",
      classLevel: "Class 12",
      topicName: "Genetics",
      ncertChapter: "Chapter 5: Principles of Inheritance and Variation",
      referenceBooks: ["Trueman's Biology Class 12"],
    },
  ]).returning();

  // Create topics for Zoology
  const zoologyTopics = await db.insert(contentTopics).values([
    {
      subject: "Zoology",
      classLevel: "Class 11",
      topicName: "Human Physiology",
      ncertChapter: "Chapter 17: Breathing and Exchange of Gases",
      referenceBooks: ["Trueman's Biology Class 11"],
    },
    {
      subject: "Zoology",
      classLevel: "Class 12",
      topicName: "Reproduction",
      ncertChapter: "Chapter 2: Sexual Reproduction in Flowering Plants",
      referenceBooks: ["Trueman's Biology Class 12"],
    },
    {
      subject: "Zoology",
      classLevel: "Class 12",
      topicName: "Evolution",
      ncertChapter: "Chapter 7: Evolution",
      referenceBooks: ["Trueman's Biology Class 12"],
    },
  ]).returning();

  console.log("Topics created successfully");

  // Seed Physics questions
  await db.insert(questions).values([
    {
      topicId: physicsTopics[0].id,
      questionText: "A particle moves in a straight line with constant acceleration. If it covers 100 m in the first 10 seconds and 150 m in the next 10 seconds, what is its acceleration?",
      options: [
        { id: "A", text: "0.5 m/s²" },
        { id: "B", text: "1.0 m/s²" },
        { id: "C", text: "1.5 m/s²" },
        { id: "D", text: "2.0 m/s²" },
      ],
      correctAnswer: "A",
      solutionDetail: "The particle's motion can be analyzed using equations of motion. Since the distance covered in successive equal time intervals is different, the particle must have constant acceleration.",
      solutionSteps: [
        "Using s = ut + (1/2)at², for first 10 seconds: 100 = 10u + 50a",
        "For next 10 seconds (total 20s): 250 = 20u + 200a",
        "Solving these simultaneous equations: From equation 1: u = (100 - 50a)/10",
        "Substituting in equation 2 and solving: a = 0.5 m/s²",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT Example",
      relatedTopics: ["Equations of Motion", "Uniformly Accelerated Motion"],
    },
    {
      topicId: physicsTopics[0].id,
      questionText: "A car travels at 60 km/h for 1 hour and then at 90 km/h for another hour. What is the average speed of the car?",
      options: [
        { id: "A", text: "70 km/h" },
        { id: "B", text: "72 km/h" },
        { id: "C", text: "75 km/h" },
        { id: "D", text: "80 km/h" },
      ],
      correctAnswer: "C",
      solutionDetail: "Average speed is the total distance traveled divided by total time taken.",
      solutionSteps: [
        "Distance in first hour = 60 km",
        "Distance in second hour = 90 km",
        "Total distance = 60 + 90 = 150 km",
        "Total time = 1 + 1 = 2 hours",
        "Average speed = 150/2 = 75 km/h",
      ],
      difficultyLevel: 1,
      sourceType: "NCERT",
      relatedTopics: ["Average Speed", "Kinematics"],
    },
    {
      topicId: physicsTopics[0].id,
      questionText: "A stone is dropped from the top of a tower 500 m high. Ignoring air resistance, what is its velocity when it reaches the ground? (g = 10 m/s²)",
      options: [
        { id: "A", text: "50 m/s" },
        { id: "B", text: "100 m/s" },
        { id: "C", text: "200 m/s" },
        { id: "D", text: "500 m/s" },
      ],
      correctAnswer: "B",
      solutionDetail: "Using the third equation of motion for free fall: v² = u² + 2as",
      solutionSteps: [
        "Initial velocity u = 0 (dropped from rest)",
        "Acceleration a = g = 10 m/s²",
        "Distance s = 500 m",
        "v² = 0 + 2 × 10 × 500 = 10,000",
        "v = 100 m/s",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT Exercise",
      relatedTopics: ["Free Fall", "Equations of Motion"],
    },
    {
      topicId: physicsTopics[0].id,
      questionText: "A body starts from rest and moves with uniform acceleration of 2 m/s². What distance will it cover in the 5th second of its motion?",
      options: [
        { id: "A", text: "8 m" },
        { id: "B", text: "9 m" },
        { id: "C", text: "10 m" },
        { id: "D", text: "11 m" },
      ],
      correctAnswer: "B",
      solutionDetail: "Distance covered in the nth second is given by: sₙ = u + a(n - 1/2)",
      solutionSteps: [
        "Initial velocity u = 0",
        "Acceleration a = 2 m/s²",
        "For 5th second, n = 5",
        "s₅ = 0 + 2(5 - 0.5) = 2 × 4.5 = 9 m",
      ],
      difficultyLevel: 2,
      sourceType: "HC Verma",
      relatedTopics: ["Distance in nth Second", "Uniformly Accelerated Motion"],
    },
    {
      topicId: physicsTopics[1].id,
      questionText: "A block of mass 2 kg is placed on a horizontal surface. If the coefficient of friction is 0.3, what is the maximum force of friction that can act on the block? (g = 10 m/s²)",
      options: [
        { id: "A", text: "4 N" },
        { id: "B", text: "6 N" },
        { id: "C", text: "8 N" },
        { id: "D", text: "10 N" },
      ],
      correctAnswer: "B",
      solutionDetail: "The maximum force of static friction is given by f = μN, where μ is the coefficient of friction and N is the normal force.",
      solutionSteps: [
        "Normal force N = mg = 2 × 10 = 20 N",
        "Maximum friction f = μN = 0.3 × 20 = 6 N",
      ],
      difficultyLevel: 1,
      sourceType: "NCERT",
      relatedTopics: ["Friction", "Newton's Laws"],
    },
    {
      topicId: physicsTopics[1].id,
      questionText: "Two blocks of masses 3 kg and 5 kg are connected by a string passing over a frictionless pulley. What is the acceleration of the system? (g = 10 m/s²)",
      options: [
        { id: "A", text: "2.5 m/s²" },
        { id: "B", text: "3.0 m/s²" },
        { id: "C", text: "3.5 m/s²" },
        { id: "D", text: "4.0 m/s²" },
      ],
      correctAnswer: "A",
      solutionDetail: "For two masses connected by a pulley, acceleration a = (m₂ - m₁)g/(m₁ + m₂)",
      solutionSteps: [
        "Let m₁ = 3 kg, m₂ = 5 kg",
        "a = (5 - 3) × 10 / (3 + 5)",
        "a = 20 / 8 = 2.5 m/s²",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT Example",
      relatedTopics: ["Pulley Systems", "Newton's Second Law"],
    },
    {
      topicId: physicsTopics[1].id,
      questionText: "A force of 10 N acts on a body of mass 2 kg for 5 seconds. If the body was initially at rest, what is its final velocity?",
      options: [
        { id: "A", text: "20 m/s" },
        { id: "B", text: "25 m/s" },
        { id: "C", text: "30 m/s" },
        { id: "D", text: "50 m/s" },
      ],
      correctAnswer: "B",
      solutionDetail: "Using Newton's second law F = ma and first equation of motion v = u + at",
      solutionSteps: [
        "Acceleration a = F/m = 10/2 = 5 m/s²",
        "Initial velocity u = 0",
        "Time t = 5 s",
        "Final velocity v = 0 + 5 × 5 = 25 m/s",
      ],
      difficultyLevel: 1,
      sourceType: "NCERT",
      relatedTopics: ["Newton's Second Law", "Force and Motion"],
    },
    {
      topicId: physicsTopics[2].id,
      questionText: "Two point charges +3 μC and -3 μC are separated by a distance of 6 cm. What is the electric field at the midpoint between them?",
      options: [
        { id: "A", text: "0 N/C" },
        { id: "B", text: "3 × 10⁶ N/C" },
        { id: "C", text: "6 × 10⁶ N/C" },
        { id: "D", text: "12 × 10⁶ N/C" },
      ],
      correctAnswer: "C",
      solutionDetail: "The electric field at the midpoint is the vector sum of fields due to both charges. Since the charges are equal and opposite, the fields add up.",
      solutionSteps: [
        "Distance from each charge to midpoint r = 3 cm = 0.03 m",
        "Electric field due to +3 μC: E₁ = kq/r² pointing away",
        "Electric field due to -3 μC: E₂ = kq/r² pointing toward the charge",
        "Both fields point in the same direction (from + to -)",
        "Total field = 2 × (9×10⁹ × 3×10⁻⁶)/(0.03)² = 6 × 10⁶ N/C",
      ],
      difficultyLevel: 3,
      sourceType: "PYQ 2023",
      relatedTopics: ["Electric Field", "Point Charges"],
    },
    {
      topicId: physicsTopics[2].id,
      questionText: "The electric potential at a point due to a charge of 5 μC at a distance of 0.5 m is:",
      options: [
        { id: "A", text: "9 × 10⁴ V" },
        { id: "B", text: "9 × 10⁵ V" },
        { id: "C", text: "4.5 × 10⁴ V" },
        { id: "D", text: "4.5 × 10⁵ V" },
      ],
      correctAnswer: "A",
      solutionDetail: "Electric potential V = kq/r",
      solutionSteps: [
        "k = 9 × 10⁹ N·m²/C²",
        "q = 5 μC = 5 × 10⁻⁶ C",
        "r = 0.5 m",
        "V = (9 × 10⁹ × 5 × 10⁻⁶) / 0.5",
        "V = 9 × 10⁴ V",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Electric Potential", "Point Charges"],
    },
    {
      topicId: physicsTopics[2].id,
      questionText: "A parallel plate capacitor has capacitance 100 μF. If the potential difference between plates is 50 V, what is the charge stored?",
      options: [
        { id: "A", text: "5 mC" },
        { id: "B", text: "50 mC" },
        { id: "C", text: "0.5 mC" },
        { id: "D", text: "500 mC" },
      ],
      correctAnswer: "A",
      solutionDetail: "Charge stored in a capacitor: Q = CV",
      solutionSteps: [
        "C = 100 μF = 100 × 10⁻⁶ F",
        "V = 50 V",
        "Q = 100 × 10⁻⁶ × 50",
        "Q = 5 × 10⁻³ C = 5 mC",
      ],
      difficultyLevel: 1,
      sourceType: "NCERT Exercise",
      relatedTopics: ["Capacitance", "Charge Storage"],
    },
  ]);

  // Seed Chemistry questions
  await db.insert(questions).values([
    {
      topicId: chemistryTopics[0].id,
      questionText: "The maximum number of electrons in a subshell with l = 3 is:",
      options: [
        { id: "A", text: "2" },
        { id: "B", text: "6" },
        { id: "C", text: "10" },
        { id: "D", text: "14" },
      ],
      correctAnswer: "D",
      solutionDetail: "For a given value of l (azimuthal quantum number), the maximum number of electrons is given by 2(2l + 1).",
      solutionSteps: [
        "Given: l = 3 (f subshell)",
        "Number of orbitals = 2l + 1 = 2(3) + 1 = 7",
        "Each orbital can hold 2 electrons",
        "Maximum electrons = 2 × 7 = 14",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Quantum Numbers", "Electronic Configuration"],
    },
    {
      topicId: chemistryTopics[0].id,
      questionText: "The energy of an electron in the second orbit of hydrogen atom is:",
      options: [
        { id: "A", text: "-13.6 eV" },
        { id: "B", text: "-3.4 eV" },
        { id: "C", text: "-1.51 eV" },
        { id: "D", text: "-0.85 eV" },
      ],
      correctAnswer: "B",
      solutionDetail: "Energy of electron in nth orbit is given by: Eₙ = -13.6/n² eV",
      solutionSteps: [
        "For hydrogen atom, E₁ = -13.6 eV",
        "For second orbit, n = 2",
        "E₂ = -13.6/2² = -13.6/4",
        "E₂ = -3.4 eV",
      ],
      difficultyLevel: 1,
      sourceType: "NCERT",
      relatedTopics: ["Bohr's Model", "Energy Levels"],
    },
    {
      topicId: chemistryTopics[0].id,
      questionText: "What is the wavelength of radiation emitted when an electron in a hydrogen atom jumps from n=3 to n=2? (Rydberg constant R = 1.097 × 10⁷ m⁻¹)",
      options: [
        { id: "A", text: "486 nm" },
        { id: "B", text: "656 nm" },
        { id: "C", text: "434 nm" },
        { id: "D", text: "410 nm" },
      ],
      correctAnswer: "B",
      solutionDetail: "Using Rydberg formula: 1/λ = R(1/n₁² - 1/n₂²)",
      solutionSteps: [
        "n₁ = 2, n₂ = 3",
        "1/λ = 1.097 × 10⁷ (1/4 - 1/9)",
        "1/λ = 1.097 × 10⁷ × 5/36",
        "λ = 6.56 × 10⁻⁷ m = 656 nm",
        "This is the Hα line in Balmer series",
      ],
      difficultyLevel: 3,
      sourceType: "NCERT Example",
      relatedTopics: ["Hydrogen Spectrum", "Balmer Series"],
    },
    {
      topicId: chemistryTopics[0].id,
      questionText: "The electronic configuration of Cr (Z=24) is:",
      options: [
        { id: "A", text: "[Ar] 3d⁴ 4s²" },
        { id: "B", text: "[Ar] 3d⁵ 4s¹" },
        { id: "C", text: "[Ar] 3d⁶ 4s⁰" },
        { id: "D", text: "[Ar] 3d³ 4s³" },
      ],
      correctAnswer: "B",
      solutionDetail: "Chromium shows exceptional configuration due to stability of half-filled d subshell.",
      solutionSteps: [
        "Expected configuration: [Ar] 3d⁴ 4s²",
        "Half-filled d⁵ is more stable than d⁴",
        "One electron from 4s moves to 3d",
        "Actual configuration: [Ar] 3d⁵ 4s¹",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Electronic Configuration", "Exceptional Configurations"],
    },
    {
      topicId: chemistryTopics[1].id,
      questionText: "Which of the following molecules has a linear shape?",
      options: [
        { id: "A", text: "H₂O" },
        { id: "B", text: "CO₂" },
        { id: "C", text: "NH₃" },
        { id: "D", text: "CH₄" },
      ],
      correctAnswer: "B",
      solutionDetail: "CO₂ has a linear molecular geometry due to sp hybridization of carbon and absence of lone pairs.",
      solutionSteps: [
        "CO₂: Carbon has sp hybridization, two C=O double bonds, bond angle 180°",
        "H₂O: Bent shape due to lone pairs on oxygen",
        "NH₃: Pyramidal shape due to lone pair on nitrogen",
        "CH₄: Tetrahedral shape with sp³ hybridization",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["VSEPR Theory", "Molecular Geometry", "Hybridization"],
    },
    {
      topicId: chemistryTopics[1].id,
      questionText: "The bond angle in NH₃ molecule is:",
      options: [
        { id: "A", text: "109.5°" },
        { id: "B", text: "107.5°" },
        { id: "C", text: "104.5°" },
        { id: "D", text: "120°" },
      ],
      correctAnswer: "B",
      solutionDetail: "NH₃ has pyramidal shape with sp³ hybridization and one lone pair.",
      solutionSteps: [
        "Nitrogen is sp³ hybridized",
        "One lone pair on nitrogen",
        "Lone pair-bond pair repulsion > bond pair-bond pair repulsion",
        "Bond angle reduces from 109.5° to 107.5°",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["VSEPR Theory", "Bond Angles"],
    },
    {
      topicId: chemistryTopics[1].id,
      questionText: "Which of the following has the highest ionic character?",
      options: [
        { id: "A", text: "NaCl" },
        { id: "B", text: "MgCl₂" },
        { id: "C", text: "AlCl₃" },
        { id: "D", text: "SiCl₄" },
      ],
      correctAnswer: "A",
      solutionDetail: "Ionic character increases with greater electronegativity difference and smaller cation size.",
      solutionSteps: [
        "Na⁺ has largest size and lowest charge density",
        "As we go from Na to Si, cation size decreases",
        "Polarizing power increases: Na⁺ < Mg²⁺ < Al³⁺ < Si⁴⁺",
        "NaCl has highest ionic character (least covalent)",
      ],
      difficultyLevel: 2,
      sourceType: "P. Bahadur",
      relatedTopics: ["Ionic Character", "Fajans Rules"],
    },
    {
      topicId: chemistryTopics[1].id,
      questionText: "The number of sigma and pi bonds in benzene (C₆H₆) are:",
      options: [
        { id: "A", text: "12 σ, 3 π" },
        { id: "B", text: "9 σ, 3 π" },
        { id: "C", text: "6 σ, 6 π" },
        { id: "D", text: "12 σ, 6 π" },
      ],
      correctAnswer: "A",
      solutionDetail: "Benzene has 6 C-C σ bonds, 6 C-H σ bonds, and 3 delocalized π bonds.",
      solutionSteps: [
        "6 C-C single bonds = 6 σ bonds",
        "6 C-H bonds = 6 σ bonds",
        "Total σ bonds = 12",
        "3 C=C double bonds contribute 3 π bonds",
        "Total: 12 σ and 3 π bonds",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT Example",
      relatedTopics: ["Chemical Bonding", "Benzene Structure"],
    },
    {
      topicId: chemistryTopics[2].id,
      questionText: "The standard electrode potential of Zn²⁺/Zn is -0.76 V and that of Cu²⁺/Cu is +0.34 V. What is the EMF of the cell Zn|Zn²⁺||Cu²⁺|Cu?",
      options: [
        { id: "A", text: "0.42 V" },
        { id: "B", text: "1.10 V" },
        { id: "C", text: "-0.42 V" },
        { id: "D", text: "-1.10 V" },
      ],
      correctAnswer: "B",
      solutionDetail: "The EMF of the cell is calculated using E°cell = E°cathode - E°anode.",
      solutionSteps: [
        "Given: E°(Zn²⁺/Zn) = -0.76 V, E°(Cu²⁺/Cu) = +0.34 V",
        "Zn acts as anode (oxidation), Cu acts as cathode (reduction)",
        "E°cell = E°cathode - E°anode",
        "E°cell = 0.34 - (-0.76) = 1.10 V",
      ],
      difficultyLevel: 2,
      sourceType: "PYQ 2022",
      relatedTopics: ["Electrochemical Cells", "Standard Electrode Potential"],
    },
    {
      topicId: chemistryTopics[2].id,
      questionText: "For the reaction Zn + Cu²⁺ → Zn²⁺ + Cu, if E°cell = 1.10 V, what is ΔG° at 298 K? (F = 96500 C/mol)",
      options: [
        { id: "A", text: "-106.3 kJ/mol" },
        { id: "B", text: "-212.3 kJ/mol" },
        { id: "C", text: "+106.3 kJ/mol" },
        { id: "D", text: "+212.3 kJ/mol" },
      ],
      correctAnswer: "B",
      solutionDetail: "ΔG° = -nFE°cell, where n is number of electrons transferred.",
      solutionSteps: [
        "Number of electrons transferred n = 2",
        "F = 96500 C/mol",
        "E°cell = 1.10 V",
        "ΔG° = -2 × 96500 × 1.10",
        "ΔG° = -212,300 J/mol = -212.3 kJ/mol",
      ],
      difficultyLevel: 3,
      sourceType: "NCERT Example",
      relatedTopics: ["Gibbs Free Energy", "Electrochemistry"],
    },
    {
      topicId: chemistryTopics[2].id,
      questionText: "The equivalent conductance of NaCl at infinite dilution is 126.5 S cm² eq⁻¹. If ionic conductances of Na⁺ and Cl⁻ are 50.1 and 76.4 S cm² eq⁻¹ respectively, verify Kohlrausch's law.",
      options: [
        { id: "A", text: "Law is verified" },
        { id: "B", text: "Law is not verified" },
        { id: "C", text: "Cannot determine" },
        { id: "D", text: "Data insufficient" },
      ],
      correctAnswer: "A",
      solutionDetail: "According to Kohlrausch's law: Λ° = λ°+ + λ°-",
      solutionSteps: [
        "Given: Λ°(NaCl) = 126.5 S cm² eq⁻¹",
        "λ°(Na⁺) = 50.1 S cm² eq⁻¹",
        "λ°(Cl⁻) = 76.4 S cm² eq⁻¹",
        "λ°(Na⁺) + λ°(Cl⁻) = 50.1 + 76.4 = 126.5",
        "Law is verified as both values match",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Kohlrausch's Law", "Conductance"],
    },
  ]);

  // Seed Botany questions
  await db.insert(questions).values([
    {
      topicId: botanyTopics[0].id,
      questionText: "Which organelle is known as the powerhouse of the cell?",
      options: [
        { id: "A", text: "Nucleus" },
        { id: "B", text: "Mitochondria" },
        { id: "C", text: "Chloroplast" },
        { id: "D", text: "Endoplasmic Reticulum" },
      ],
      correctAnswer: "B",
      solutionDetail: "Mitochondria are called the powerhouse of the cell because they produce ATP through cellular respiration.",
      solutionSteps: [
        "Mitochondria perform aerobic respiration",
        "They convert glucose and oxygen into ATP (energy currency)",
        "This process occurs in the inner mitochondrial membrane",
        "ATP is used for all cellular activities requiring energy",
      ],
      difficultyLevel: 1,
      sourceType: "NCERT",
      relatedTopics: ["Cell Organelles", "Cellular Respiration"],
    },
    {
      topicId: botanyTopics[0].id,
      questionText: "Which of the following is NOT a function of the plasma membrane?",
      options: [
        { id: "A", text: "Selective permeability" },
        { id: "B", text: "Protein synthesis" },
        { id: "C", text: "Cell recognition" },
        { id: "D", text: "Transport of materials" },
      ],
      correctAnswer: "B",
      solutionDetail: "Protein synthesis occurs in ribosomes, not in the plasma membrane.",
      solutionSteps: [
        "Plasma membrane controls entry and exit (selective permeability)",
        "Contains glycoproteins for cell recognition",
        "Has transport proteins for material transport",
        "Protein synthesis is the function of ribosomes",
      ],
      difficultyLevel: 1,
      sourceType: "NCERT",
      relatedTopics: ["Cell Membrane", "Cell Functions"],
    },
    {
      topicId: botanyTopics[0].id,
      questionText: "The cristae of mitochondria are sites for:",
      options: [
        { id: "A", text: "Glycolysis" },
        { id: "B", text: "Krebs cycle" },
        { id: "C", text: "Electron transport chain" },
        { id: "D", text: "Photosynthesis" },
      ],
      correctAnswer: "C",
      solutionDetail: "Cristae are the folded inner membrane of mitochondria where electron transport chain and ATP synthesis occur.",
      solutionSteps: [
        "Cristae increase surface area of inner membrane",
        "Electron transport chain proteins are embedded here",
        "ATP synthase complexes are located on cristae",
        "This is where most ATP is produced in aerobic respiration",
      ],
      difficultyLevel: 2,
      sourceType: "Trueman's Biology",
      relatedTopics: ["Mitochondrial Structure", "Cellular Respiration"],
    },
    {
      topicId: botanyTopics[1].id,
      questionText: "What is the primary product of the light reaction in photosynthesis?",
      options: [
        { id: "A", text: "Glucose" },
        { id: "B", text: "ATP and NADPH" },
        { id: "C", text: "CO₂" },
        { id: "D", text: "Oxygen only" },
      ],
      correctAnswer: "B",
      solutionDetail: "The light reactions of photosynthesis produce ATP and NADPH, which are then used in the Calvin cycle to fix CO₂ into glucose.",
      solutionSteps: [
        "Light reactions occur in thylakoid membranes",
        "Light energy is absorbed by chlorophyll",
        "Water molecules are split (photolysis), releasing O₂",
        "ATP and NADPH are produced for use in dark reactions",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Photosynthesis", "Light Reactions"],
    },
    {
      topicId: botanyTopics[1].id,
      questionText: "In C₄ plants, the first stable product of photosynthesis is:",
      options: [
        { id: "A", text: "Phosphoglyceric acid (3C)" },
        { id: "B", text: "Oxaloacetic acid (4C)" },
        { id: "C", text: "Ribulose bisphosphate (5C)" },
        { id: "D", text: "Glucose (6C)" },
      ],
      correctAnswer: "B",
      solutionDetail: "C₄ plants fix CO₂ using PEP carboxylase to form oxaloacetic acid (4-carbon compound).",
      solutionSteps: [
        "In C₄ plants, CO₂ is first fixed in mesophyll cells",
        "PEP carboxylase catalyzes the reaction",
        "PEP + CO₂ → Oxaloacetic acid (OAA)",
        "OAA is then converted to malic acid and transported to bundle sheath cells",
      ],
      difficultyLevel: 3,
      sourceType: "NCERT",
      relatedTopics: ["C₄ Pathway", "Carbon Fixation"],
    },
    {
      topicId: botanyTopics[1].id,
      questionText: "The oxygen evolved during photosynthesis comes from:",
      options: [
        { id: "A", text: "CO₂" },
        { id: "B", text: "H₂O" },
        { id: "C", text: "Both CO₂ and H₂O" },
        { id: "D", text: "Glucose" },
      ],
      correctAnswer: "B",
      solutionDetail: "Oxygen released during photosynthesis comes from photolysis of water molecules.",
      solutionSteps: [
        "This was proven by experiments using O¹⁸ isotope",
        "When H₂O¹⁸ was used, O¹⁸ was released",
        "When C¹⁸O₂ was used, no O¹⁸ was released",
        "Water splitting (photolysis): 2H₂O → 4H⁺ + 4e⁻ + O₂",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT Example",
      relatedTopics: ["Photolysis", "Light Reactions"],
    },
    {
      topicId: botanyTopics[2].id,
      questionText: "In a dihybrid cross between two heterozygous individuals (AaBb × AaBb), what is the phenotypic ratio in F₂ generation?",
      options: [
        { id: "A", text: "3:1" },
        { id: "B", text: "1:2:1" },
        { id: "C", text: "9:3:3:1" },
        { id: "D", text: "1:1:1:1" },
      ],
      correctAnswer: "C",
      solutionDetail: "According to Mendel's law of independent assortment, a dihybrid cross between two heterozygous individuals produces a 9:3:3:1 phenotypic ratio.",
      solutionSteps: [
        "Each parent produces four types of gametes: AB, Ab, aB, ab",
        "16 possible combinations in F₂ generation",
        "9 show both dominant traits (A_B_)",
        "3 show first dominant, second recessive (A_bb)",
        "3 show first recessive, second dominant (aaB_)",
        "1 shows both recessive traits (aabb)",
      ],
      difficultyLevel: 3,
      sourceType: "NCERT Example",
      relatedTopics: ["Mendelian Genetics", "Dihybrid Cross", "Law of Independent Assortment"],
    },
    {
      topicId: botanyTopics[2].id,
      questionText: "A cross between a tall plant (TT) and a dwarf plant (tt) in F₁ generation produces:",
      options: [
        { id: "A", text: "All tall plants" },
        { id: "B", text: "All dwarf plants" },
        { id: "C", text: "50% tall, 50% dwarf" },
        { id: "D", text: "75% tall, 25% dwarf" },
      ],
      correctAnswer: "A",
      solutionDetail: "This is a monohybrid cross where tall (T) is dominant over dwarf (t).",
      solutionSteps: [
        "Parent 1: TT (homozygous tall)",
        "Parent 2: tt (homozygous dwarf)",
        "All F₁ offspring will be Tt (heterozygous)",
        "Since T is dominant, all F₁ plants will be tall",
      ],
      difficultyLevel: 1,
      sourceType: "NCERT",
      relatedTopics: ["Monohybrid Cross", "Dominance"],
    },
    {
      topicId: botanyTopics[2].id,
      questionText: "In incomplete dominance, the F₁ hybrid:",
      options: [
        { id: "A", text: "Resembles either of the parents" },
        { id: "B", text: "Shows intermediate phenotype" },
        { id: "C", text: "Shows both parental phenotypes" },
        { id: "D", text: "Shows dominant phenotype only" },
      ],
      correctAnswer: "B",
      solutionDetail: "In incomplete dominance, neither allele is completely dominant, resulting in a blended phenotype.",
      solutionSteps: [
        "Neither allele is completely dominant",
        "F₁ shows intermediate phenotype",
        "Example: Red (RR) × White (rr) → Pink (Rr)",
        "F₂ ratio becomes 1:2:1 (phenotypic = genotypic)",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Incomplete Dominance", "Non-Mendelian Inheritance"],
    },
  ]);

  // Seed Zoology questions
  await db.insert(questions).values([
    {
      topicId: zoologyTopics[0].id,
      questionText: "The respiratory center in humans is located in:",
      options: [
        { id: "A", text: "Cerebrum" },
        { id: "B", text: "Medulla oblongata" },
        { id: "C", text: "Cerebellum" },
        { id: "D", text: "Hypothalamus" },
      ],
      correctAnswer: "B",
      solutionDetail: "The medulla oblongata in the brainstem contains the respiratory center that controls breathing rate and depth.",
      solutionSteps: [
        "Medulla oblongata is part of the hindbrain",
        "It contains chemoreceptors sensitive to CO₂ levels",
        "High CO₂ triggers increased breathing rate",
        "This maintains proper blood pH and oxygen levels",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Respiratory System", "Neural Control of Breathing"],
    },
    {
      topicId: zoologyTopics[0].id,
      questionText: "The vital capacity of lungs in a normal adult human is approximately:",
      options: [
        { id: "A", text: "1000-1500 mL" },
        { id: "B", text: "2500-3000 mL" },
        { id: "C", text: "3500-4500 mL" },
        { id: "D", text: "5000-6000 mL" },
      ],
      correctAnswer: "C",
      solutionDetail: "Vital capacity is the maximum volume of air that can be exhaled after maximum inspiration.",
      solutionSteps: [
        "Vital capacity = IRV + TV + ERV",
        "Inspiratory Reserve Volume (IRV) ≈ 2500-3000 mL",
        "Tidal Volume (TV) ≈ 500 mL",
        "Expiratory Reserve Volume (ERV) ≈ 1000-1100 mL",
        "Total VC ≈ 3500-4500 mL",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Lung Volumes", "Respiratory Physiology"],
    },
    {
      topicId: zoologyTopics[0].id,
      questionText: "Which of the following has the highest affinity for hemoglobin?",
      options: [
        { id: "A", text: "O₂" },
        { id: "B", text: "CO₂" },
        { id: "C", text: "CO" },
        { id: "D", text: "N₂" },
      ],
      correctAnswer: "C",
      solutionDetail: "Carbon monoxide (CO) has about 200-250 times higher affinity for hemoglobin than oxygen.",
      solutionSteps: [
        "CO binds to hemoglobin forming carboxyhemoglobin",
        "This binding is almost irreversible",
        "CO prevents oxygen binding to hemoglobin",
        "This is why CO poisoning is fatal",
      ],
      difficultyLevel: 2,
      sourceType: "Trueman's Biology",
      relatedTopics: ["Hemoglobin", "Gas Transport", "Carbon Monoxide Poisoning"],
    },
    {
      topicId: zoologyTopics[1].id,
      questionText: "Fertilization in humans normally occurs in:",
      options: [
        { id: "A", text: "Ovary" },
        { id: "B", text: "Uterus" },
        { id: "C", text: "Fallopian tube (ampulla)" },
        { id: "D", text: "Cervix" },
      ],
      correctAnswer: "C",
      solutionDetail: "Fertilization typically occurs in the ampullary region (widest part) of the fallopian tube, where sperm meets the ovum.",
      solutionSteps: [
        "Ovulation releases egg from ovary",
        "Egg is captured by fimbriae of fallopian tube",
        "Egg travels to ampullary region",
        "Sperm travels up from uterus to fallopian tube",
        "Fertilization occurs in ampulla within 12-24 hours",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Human Reproduction", "Fertilization"],
    },
    {
      topicId: zoologyTopics[1].id,
      questionText: "The acrosome of sperm contains:",
      options: [
        { id: "A", text: "Mitochondria" },
        { id: "B", text: "Enzymes for penetrating ovum" },
        { id: "C", text: "Genetic material" },
        { id: "D", text: "Centrioles" },
      ],
      correctAnswer: "B",
      solutionDetail: "The acrosome is a cap-like structure containing hydrolytic enzymes that help sperm penetrate the egg.",
      solutionSteps: [
        "Acrosome is derived from Golgi apparatus",
        "Contains enzymes like hyaluronidase and acrosin",
        "These enzymes digest zona pellucida of ovum",
        "Allows sperm nucleus to enter the egg",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Sperm Structure", "Fertilization"],
    },
    {
      topicId: zoologyTopics[1].id,
      questionText: "Implantation of blastocyst occurs on which day after fertilization?",
      options: [
        { id: "A", text: "3-4 days" },
        { id: "B", text: "5-6 days" },
        { id: "C", text: "7-8 days" },
        { id: "D", text: "10-12 days" },
      ],
      correctAnswer: "C",
      solutionDetail: "The blastocyst implants in the endometrium approximately 7-8 days after fertilization.",
      solutionSteps: [
        "Fertilization occurs in fallopian tube (day 0)",
        "Zygote undergoes cleavage while moving to uterus",
        "By day 5-6, blastocyst forms",
        "On day 7-8, blastocyst implants in uterine wall",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Implantation", "Early Development"],
    },
    {
      topicId: zoologyTopics[2].id,
      questionText: "According to Darwin's theory, which of the following is the most important factor in evolution?",
      options: [
        { id: "A", text: "Mutation" },
        { id: "B", text: "Natural selection" },
        { id: "C", text: "Genetic drift" },
        { id: "D", text: "Gene flow" },
      ],
      correctAnswer: "B",
      solutionDetail: "Darwin proposed that natural selection is the primary mechanism of evolution, where organisms with favorable variations survive and reproduce more successfully.",
      solutionSteps: [
        "Variation exists within populations",
        "More offspring are produced than can survive",
        "Competition for limited resources occurs",
        "Individuals with advantageous traits survive (survival of the fittest)",
        "These traits are passed to next generation",
        "Population gradually changes over time",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Natural Selection", "Darwin's Theory", "Evolution"],
    },
    {
      topicId: zoologyTopics[2].id,
      questionText: "Homologous organs indicate:",
      options: [
        { id: "A", text: "Convergent evolution" },
        { id: "B", text: "Divergent evolution" },
        { id: "C", text: "Adaptive radiation" },
        { id: "D", text: "Both B and C" },
      ],
      correctAnswer: "D",
      solutionDetail: "Homologous organs show divergent evolution and adaptive radiation from a common ancestor.",
      solutionSteps: [
        "Homologous organs have same basic structure",
        "They have different functions (divergent evolution)",
        "Example: Forelimbs of mammals",
        "Adaptive radiation occurs when species diversify from common ancestor",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Homologous Organs", "Divergent Evolution"],
    },
    {
      topicId: zoologyTopics[2].id,
      questionText: "The theory of chemical evolution of life was proposed by:",
      options: [
        { id: "A", text: "Charles Darwin" },
        { id: "B", text: "Oparin and Haldane" },
        { id: "C", text: "Hugo de Vries" },
        { id: "D", text: "Lamarck" },
      ],
      correctAnswer: "B",
      solutionDetail: "Oparin (1924) and Haldane (1929) independently proposed the theory of chemical evolution.",
      solutionSteps: [
        "They proposed life originated from non-living matter",
        "Early Earth had reducing atmosphere",
        "Simple organic molecules formed from inorganic precursors",
        "These molecules combined to form complex molecules",
        "Eventually led to formation of first living cells",
      ],
      difficultyLevel: 2,
      sourceType: "NCERT",
      relatedTopics: ["Origin of Life", "Chemical Evolution"],
    },
  ]);

  console.log("✅ Database seeded successfully with sample NEET questions!");
  process.exit(0);
}

seed().catch((error) => {
  console.error("❌ Error seeding database:", error);
  process.exit(1);
});
