import { db } from "../db";
import { contentTopics, questions } from "../../shared/schema";
import { and, eq, sql } from "drizzle-orm";

type QuestionSeed = {
  questionText: string;
  options: { id: string; text: string }[];
  correctAnswer: string;
  solutionDetail: string;
  solutionSteps?: string[];
  difficultyLevel: number;
  sourceType: string;
  relatedTopics: string[];
  pyqYear?: number | null;
};

type ChapterSeed = {
  chapterNumber: number;
  topicName: string;
  questions: QuestionSeed[];
};

const makeOptions = (a: string, b: string, c: string, d: string) => [
  { id: "A", text: a },
  { id: "B", text: b },
  { id: "C", text: c },
  { id: "D", text: d },
];

const chapters: ChapterSeed[] = [
  {
    chapterNumber: 1,
    topicName: "The Solid State",
    questions: [
      {
        questionText: "Number of atoms per unit cell in bcc is:",
        options: makeOptions("1", "2", "4", "6"),
        correctAnswer: "B",
        solutionDetail: "bcc has 2 atoms per unit cell (1 from corners and 1 from body center).",
        solutionSteps: ["Count atom contributions in bcc."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["The Solid State", "Chapter 1"],
      },
      {
        questionText: "Packing efficiency of hcp is:",
        options: makeOptions("52.4%", "68%", "74%", "100%"),
        correctAnswer: "C",
        solutionDetail: "hcp and fcc have packing efficiency of 74 percent.",
        solutionSteps: ["Recall close packing efficiency."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["The Solid State", "Chapter 1"],
        pyqYear: 2018,
      },
      {
        questionText: "Coordination number in fcc is:",
        options: makeOptions("6", "8", "12", "14"),
        correctAnswer: "C",
        solutionDetail: "Each atom in fcc has 12 nearest neighbors.",
        solutionSteps: ["Recall coordination numbers of lattices."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["The Solid State", "Chapter 1"],
      },
      {
        questionText: "A tetrahedral void is surrounded by:",
        options: makeOptions("4 atoms", "6 atoms", "8 atoms", "12 atoms"),
        correctAnswer: "A",
        solutionDetail: "Tetrahedral void is formed by four spheres at corners of a tetrahedron.",
        solutionSteps: ["Recall void types in close packing."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["The Solid State", "Chapter 1"],
      },
      {
        questionText: "Schottky defect leads to:",
        options: makeOptions("Decrease in density", "Increase in density", "No change in density", "Color change only"),
        correctAnswer: "A",
        solutionDetail: "Schottky defect removes ions from lattice, decreasing density.",
        solutionSteps: ["Recall effect of Schottky defects."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["The Solid State", "Chapter 1"],
        pyqYear: 2020,
      },
      {
        questionText: "F-center in NaCl is due to:",
        options: makeOptions(
          "Electron trapped in anion vacancy",
          "Cation vacancy only",
          "Interstitial anion",
          "Interstitial cation"
        ),
        correctAnswer: "A",
        solutionDetail: "F-center is an anion vacancy occupied by an electron.",
        solutionSteps: ["Recall defect responsible for color."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["The Solid State", "Chapter 1"],
      },
    ],
  },
  {
    chapterNumber: 2,
    topicName: "Solutions",
    questions: [
      {
        questionText: "Raoult's law is obeyed by:",
        options: makeOptions("Ideal solutions", "Non ideal solutions", "Colloids", "Suspensions"),
        correctAnswer: "A",
        solutionDetail: "Raoult's law is valid for ideal solutions.",
        solutionSteps: ["Recall conditions for Raoult's law."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Solutions", "Chapter 2"],
      },
      {
        questionText: "Elevation of boiling point is given by:",
        options: makeOptions("delta Tb = Kb * m", "delta Tb = Kf * m", "pi = C R T", "p = kH x"),
        correctAnswer: "A",
        solutionDetail: "Boiling point elevation is delta Tb = Kb * m.",
        solutionSteps: ["Recall colligative property formulas."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Solutions", "Chapter 2"],
      },
      {
        questionText: "Which concentration unit is temperature independent?",
        options: makeOptions("Molality", "Molarity", "Normality", "Formality"),
        correctAnswer: "A",
        solutionDetail: "Molality depends on mass of solvent and is temperature independent.",
        solutionSteps: ["Recall temperature dependence of concentration units."],
        difficultyLevel: 1,
        sourceType: "pyq",
        relatedTopics: ["Solutions", "Chapter 2"],
        pyqYear: 2019,
      },
      {
        questionText: "Vapor pressure of a solution with non volatile solute is:",
        options: makeOptions("Lower than pure solvent", "Higher than pure solvent", "Equal to pure solvent", "Zero always"),
        correctAnswer: "A",
        solutionDetail: "Non volatile solute lowers vapor pressure of solvent.",
        solutionSteps: ["Recall Raoult's law consequence."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Solutions", "Chapter 2"],
      },
      {
        questionText: "An azeotrope is a mixture that:",
        options: makeOptions("Boils at constant composition", "Always shows ideal behavior", "Never distills", "Contains solids"),
        correctAnswer: "A",
        solutionDetail: "Azeotropes boil at constant composition and cannot be separated by simple distillation.",
        solutionSteps: ["Recall definition of azeotrope."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Solutions", "Chapter 2"],
      },
      {
        questionText: "van't Hoff factor for K2SO4 (complete dissociation) is:",
        options: makeOptions("1", "2", "3", "4"),
        correctAnswer: "C",
        solutionDetail: "K2SO4 dissociates into 2K+ and SO4 2-, giving i about 3.",
        solutionSteps: ["Count ions formed per formula unit."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Solutions", "Chapter 2"],
      },
    ],
  },
  {
    chapterNumber: 3,
    topicName: "Electrochemistry",
    questions: [
      {
        questionText: "The relation between Gibbs free energy and cell potential is:",
        options: makeOptions("Delta G = -n F Ecell", "Delta G = n F Ecell", "Delta G = -R T ln K", "Delta G = K Ecell"),
        correctAnswer: "A",
        solutionDetail: "Delta G equals -n F Ecell for an electrochemical cell.",
        solutionSteps: ["Recall thermodynamic relation."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Electrochemistry", "Chapter 3"],
      },
      {
        questionText: "At equilibrium, the cell potential Ecell is:",
        options: makeOptions("0", "Positive", "Negative", "Infinity"),
        correctAnswer: "A",
        solutionDetail: "At equilibrium, Ecell becomes zero.",
        solutionSteps: ["Recall equilibrium condition."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Electrochemistry", "Chapter 3"],
      },
      {
        questionText: "Molar conductivity of strong electrolytes increases with:",
        options: makeOptions("Dilution", "Concentration", "Pressure", "No change"),
        correctAnswer: "A",
        solutionDetail: "Dilution reduces inter ionic interactions, increasing molar conductivity.",
        solutionSteps: ["Recall conductivity trends."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Electrochemistry", "Chapter 3"],
      },
      {
        questionText: "Kohlrausch law for strong electrolytes is:",
        options: makeOptions("Lambda_m = Lambda_m0 - K sqrt(c)", "Lambda_m = K c", "Lambda_m = K / c", "Lambda_m = Lambda_m0 + K c"),
        correctAnswer: "A",
        solutionDetail: "Kohlrausch law gives Lambda_m = Lambda_m0 - K sqrt(c).",
        solutionSteps: ["Recall Kohlrausch equation."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Electrochemistry", "Chapter 3"],
        pyqYear: 2019,
      },
      {
        questionText: "In an electrolytic cell, the anode is:",
        options: makeOptions("Positive", "Negative", "Neutral", "Depends on electrolyte only"),
        correctAnswer: "A",
        solutionDetail: "In electrolytic cells, the anode is positive and attracts anions.",
        solutionSteps: ["Recall sign conventions for cells."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Electrochemistry", "Chapter 3"],
      },
      {
        questionText: "During electrolysis of molten NaCl, sodium is formed at the:",
        options: makeOptions("Cathode", "Anode", "Salt bridge", "Both electrodes"),
        correctAnswer: "A",
        solutionDetail: "Na+ ions are reduced at the cathode to form sodium metal.",
        solutionSteps: ["Recall electrode reactions."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Electrochemistry", "Chapter 3"],
        pyqYear: 2020,
      },
    ],
  },
  {
    chapterNumber: 4,
    topicName: "Chemical Kinetics",
    questions: [
      {
        questionText: "Rate law for a first order reaction is:",
        options: makeOptions("Rate = k[A]", "Rate = k[A]^2", "Rate = k[A][B]", "Rate = k[A]^0"),
        correctAnswer: "A",
        solutionDetail: "First order reactions follow rate = k[A].",
        solutionSteps: ["Recall first order rate law."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Chemical Kinetics", "Chapter 4"],
      },
      {
        questionText: "Unit of rate constant for a second order reaction is:",
        options: makeOptions("L mol^-1 s^-1", "s^-1", "mol L^-1 s^-1", "mol^2 L^-2 s^-1"),
        correctAnswer: "A",
        solutionDetail: "Second order rate constant has units of L mol^-1 s^-1.",
        solutionSteps: ["Use dimensional analysis of rate law."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Chemical Kinetics", "Chapter 4"],
      },
      {
        questionText: "Half life of a second order reaction is:",
        options: makeOptions("1/(k[A]0)", "0.693/k", "[A]0/k", "k/[A]0"),
        correctAnswer: "A",
        solutionDetail: "For second order, t1/2 = 1/(k[A]0).",
        solutionSteps: ["Recall half life expressions."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Chemical Kinetics", "Chapter 4"],
        pyqYear: 2018,
      },
      {
        questionText: "A catalyst works by:",
        options: makeOptions("Lowering activation energy", "Increasing activation energy", "Changing equilibrium constant", "Changing enthalpy"),
        correctAnswer: "A",
        solutionDetail: "Catalyst lowers activation energy, increasing rate.",
        solutionSteps: ["Recall catalyst role."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Chemical Kinetics", "Chapter 4"],
      },
      {
        questionText: "Rate constant generally increases with:",
        options: makeOptions("Temperature", "Pressure only", "Decrease in temperature", "No change"),
        correctAnswer: "A",
        solutionDetail: "Higher temperature increases rate constant via Arrhenius equation.",
        solutionSteps: ["Recall temperature dependence."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Chemical Kinetics", "Chapter 4"],
      },
      {
        questionText: "Hydrolysis of ester in excess water is an example of:",
        options: makeOptions("Pseudo first order reaction", "Zero order reaction", "Second order reaction", "Third order reaction"),
        correctAnswer: "A",
        solutionDetail: "Excess water keeps concentration constant, giving pseudo first order behavior.",
        solutionSteps: ["Recall pseudo first order examples."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Chemical Kinetics", "Chapter 4"],
        pyqYear: 2020,
      },
    ],
  },
  {
    chapterNumber: 5,
    topicName: "Surface Chemistry",
    questions: [
      {
        questionText: "Lyophilic sols are generally:",
        options: makeOptions("Reversible and stable", "Irreversible and unstable", "Always precipitated", "Non colloidal"),
        correctAnswer: "A",
        solutionDetail: "Lyophilic sols are stable and can be easily re formed.",
        solutionSteps: ["Recall properties of lyophilic sols."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Surface Chemistry", "Chapter 5"],
      },
      {
        questionText: "Micelles are formed above:",
        options: makeOptions("Critical micelle concentration", "Boiling point", "Freezing point", "Isoelectric point"),
        correctAnswer: "A",
        solutionDetail: "Micelles form when surfactant concentration exceeds CMC.",
        solutionSteps: ["Recall CMC definition."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Surface Chemistry", "Chapter 5"],
      },
      {
        questionText: "Emulsions are stabilized by:",
        options: makeOptions("Emulsifiers", "Electrolytes only", "Heating only", "Cooling only"),
        correctAnswer: "A",
        solutionDetail: "Emulsifiers stabilize emulsions by reducing interfacial tension.",
        solutionSteps: ["Recall role of emulsifiers."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Surface Chemistry", "Chapter 5"],
      },
      {
        questionText: "Chemisorption is characterized by:",
        options: makeOptions("Specificity and activation energy", "Low temperature only", "Multilayer adsorption", "Very weak forces"),
        correctAnswer: "A",
        solutionDetail: "Chemisorption is specific and involves activation energy.",
        solutionSteps: ["Recall features of chemisorption."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Surface Chemistry", "Chapter 5"],
        pyqYear: 2017,
      },
      {
        questionText: "Coagulation of a lyophobic sol can be achieved by:",
        options: makeOptions("Adding electrolytes", "Adding more solvent", "Dilution only", "Cooling only"),
        correctAnswer: "A",
        solutionDetail: "Electrolytes neutralize charges and cause coagulation.",
        solutionSteps: ["Recall coagulation method."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Surface Chemistry", "Chapter 5"],
      },
      {
        questionText: "According to Hardy Schulze rule, coagulating power:",
        options: makeOptions("Increases with valency of ion", "Decreases with valency", "Is independent of valency", "Depends only on temperature"),
        correctAnswer: "A",
        solutionDetail: "Higher valency ions have greater coagulating power.",
        solutionSteps: ["Recall Hardy Schulze rule."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Surface Chemistry", "Chapter 5"],
        pyqYear: 2019,
      },
    ],
  },
  {
    chapterNumber: 6,
    topicName: "General Principles and Processes of Isolation of Elements",
    questions: [
      {
        questionText: "Calcination is heating an ore:",
        options: makeOptions("In limited or no air", "In excess air", "In water", "With CO2"),
        correctAnswer: "A",
        solutionDetail: "Calcination removes volatile impurities in limited air.",
        solutionSteps: ["Recall definition of calcination."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Isolation of Elements", "Chapter 6"],
      },
      {
        questionText: "Roasting involves heating an ore:",
        options: makeOptions("In excess air", "In vacuum", "In water", "Without oxygen"),
        correctAnswer: "A",
        solutionDetail: "Roasting is done in excess air, especially for sulfide ores.",
        solutionSteps: ["Recall definition of roasting."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Isolation of Elements", "Chapter 6"],
      },
      {
        questionText: "Ellingham diagram plots:",
        options: makeOptions("Delta G versus temperature", "Enthalpy versus pressure", "Entropy versus volume", "Potential versus time"),
        correctAnswer: "A",
        solutionDetail: "Ellingham diagram shows temperature dependence of Gibbs energy for oxidation.",
        solutionSteps: ["Recall Ellingham diagram axes."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Isolation of Elements", "Chapter 6"],
        pyqYear: 2021,
      },
      {
        questionText: "Aluminothermic reaction can reduce:",
        options: makeOptions("Fe2O3 to Fe", "NaCl to Na", "MgO to Mg", "Al2O3 to Al"),
        correctAnswer: "A",
        solutionDetail: "Thermite reaction reduces Fe2O3 using aluminum.",
        solutionSteps: ["Recall thermite reaction."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Isolation of Elements", "Chapter 6"],
      },
      {
        questionText: "Leaching is:",
        options: makeOptions("Selective dissolution of ore in a reagent", "Roasting of ore", "Electrolysis of ore", "Smelting of ore"),
        correctAnswer: "A",
        solutionDetail: "Leaching uses a suitable reagent to dissolve the ore selectively.",
        solutionSteps: ["Recall concentration by leaching."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Isolation of Elements", "Chapter 6"],
      },
      {
        questionText: "Carbon can reduce metal oxides that lie:",
        options: makeOptions("Below carbon line in Ellingham diagram", "Above carbon line always", "Only on carbon line", "Independent of Ellingham diagram"),
        correctAnswer: "A",
        solutionDetail: "Carbon reduces oxides that are thermodynamically less stable than CO/CO2.",
        solutionSteps: ["Use Ellingham diagram criteria."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Isolation of Elements", "Chapter 6"],
      },
    ],
  },
  {
    chapterNumber: 7,
    topicName: "The p-Block Elements",
    questions: [
      {
        questionText: "Oxidizing power of halogens decreases in the order:",
        options: makeOptions("F2 > Cl2 > Br2 > I2", "I2 > Br2 > Cl2 > F2", "Cl2 > F2 > Br2 > I2", "Br2 > Cl2 > I2 > F2"),
        correctAnswer: "A",
        solutionDetail: "Oxidizing power decreases down the group due to lower electronegativity.",
        solutionSteps: ["Recall halogen trends."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["The p-Block Elements", "Chapter 7"],
      },
      {
        questionText: "Inert pair effect increases:",
        options: makeOptions("Down the group", "Up the group", "Across a period", "Not observed in p block"),
        correctAnswer: "A",
        solutionDetail: "Inert pair effect becomes more significant down the group.",
        solutionSteps: ["Recall inert pair effect trend."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["The p-Block Elements", "Chapter 7"],
      },
      {
        questionText: "White phosphorus is stored under water because:",
        options: makeOptions("It is highly reactive with oxygen", "It is insoluble in water", "It melts in water", "It is basic"),
        correctAnswer: "A",
        solutionDetail: "White phosphorus is highly reactive and can catch fire in air.",
        solutionSteps: ["Recall properties of white phosphorus."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["The p-Block Elements", "Chapter 7"],
      },
      {
        questionText: "SO2 is a:",
        options: makeOptions("Reducing agent", "Strong oxidizing agent", "Inert gas", "Base"),
        correctAnswer: "A",
        solutionDetail: "SO2 acts as a reducing agent in many reactions.",
        solutionSteps: ["Recall redox behavior of SO2."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["The p-Block Elements", "Chapter 7"],
      },
      {
        questionText: "Group 15 elements show a common oxidation state of:",
        options: makeOptions("-3", "0", "+1", "+4"),
        correctAnswer: "A",
        solutionDetail: "Group 15 elements commonly show -3 oxidation state with metals.",
        solutionSteps: ["Recall oxidation states of group 15."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["The p-Block Elements", "Chapter 7"],
      },
      {
        questionText: "The hybridization of SF6 is:",
        options: makeOptions("sp3d2", "sp3", "sp2", "dsp2"),
        correctAnswer: "A",
        solutionDetail: "SF6 has octahedral geometry with sp3d2 hybridization.",
        solutionSteps: ["Recall hybridization of SF6."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["The p-Block Elements", "Chapter 7"],
        pyqYear: 2018,
      },
    ],
  },
  {
    chapterNumber: 8,
    topicName: "The d- and f-Block Elements",
    questions: [
      {
        questionText: "Transition metals show catalytic activity because they:",
        options: makeOptions("Have variable oxidation states", "Are non metals", "Have low density", "Have fixed oxidation states"),
        correctAnswer: "A",
        solutionDetail: "Variable oxidation states allow transition metals to act as catalysts.",
        solutionSteps: ["Recall catalytic behavior of transition metals."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["The d- and f-Block Elements", "Chapter 8"],
      },
      {
        questionText: "Magnetic moment depends on:",
        options: makeOptions("Number of unpaired electrons", "Atomic number only", "Mass", "Density"),
        correctAnswer: "A",
        solutionDetail: "Magnetic moment is proportional to unpaired electrons.",
        solutionSteps: ["Recall magnetic properties of transition metals."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["The d- and f-Block Elements", "Chapter 8"],
        pyqYear: 2019,
      },
      {
        questionText: "Lanthanoid contraction is due to:",
        options: makeOptions("Poor shielding of 4f electrons", "Poor shielding of 3d electrons", "High electronegativity", "Large atomic size"),
        correctAnswer: "A",
        solutionDetail: "4f electrons shield poorly, causing contraction across lanthanoids.",
        solutionSteps: ["Recall cause of lanthanoid contraction."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["The d- and f-Block Elements", "Chapter 8"],
      },
      {
        questionText: "Most common oxidation state of lanthanoids is:",
        options: makeOptions("+3", "+2", "+4", "0"),
        correctAnswer: "A",
        solutionDetail: "Lanthanoids commonly show +3 oxidation state.",
        solutionSteps: ["Recall oxidation states of lanthanoids."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["The d- and f-Block Elements", "Chapter 8"],
      },
      {
        questionText: "Complex formation in transition metals is due to:",
        options: makeOptions("Small size and high charge", "Large size only", "Inert pair effect", "Non availability of d orbitals"),
        correctAnswer: "A",
        solutionDetail: "Small size and high charge favor complex formation.",
        solutionSteps: ["Recall factors for complex formation."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["The d- and f-Block Elements", "Chapter 8"],
      },
      {
        questionText: "Zr and Hf have similar radii because of:",
        options: makeOptions("Lanthanoid contraction", "Inert pair effect", "High electronegativity", "Large size"),
        correctAnswer: "A",
        solutionDetail: "Lanthanoid contraction makes Zr and Hf similar in size.",
        solutionSteps: ["Recall effect of lanthanoid contraction."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["The d- and f-Block Elements", "Chapter 8"],
        pyqYear: 2021,
      },
    ],
  },
  {
    chapterNumber: 9,
    topicName: "Coordination Compounds",
    questions: [
      {
        questionText: "Coordination number is defined as:",
        options: makeOptions(
          "Number of ligand donor atoms attached to central metal",
          "Oxidation state of metal",
          "Number of ions outside the bracket",
          "Total charge on complex"
        ),
        correctAnswer: "A",
        solutionDetail: "Coordination number equals number of donor atoms bound to metal.",
        solutionSteps: ["Recall coordination number definition."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Coordination Compounds", "Chapter 9"],
      },
      {
        questionText: "Chelating ligands form complexes that are:",
        options: makeOptions("More stable", "Less stable", "Always ionic", "Always neutral"),
        correctAnswer: "A",
        solutionDetail: "Chelate effect increases stability of complexes.",
        solutionSteps: ["Recall chelate effect."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Coordination Compounds", "Chapter 9"],
      },
      {
        questionText: "Geometrical isomerism is possible in:",
        options: makeOptions("Square planar and octahedral complexes", "Tetrahedral complexes only", "Linear complexes", "Ionic compounds only"),
        correctAnswer: "A",
        solutionDetail: "Square planar and octahedral complexes can show cis trans isomerism.",
        solutionSteps: ["Recall isomerism in coordination compounds."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Coordination Compounds", "Chapter 9"],
      },
      {
        questionText: "Optical isomerism is shown by:",
        options: makeOptions("[Co(en)3]3+", "[Co(NH3)6]3+", "[PtCl4]2-", "[Ni(CO)4]"),
        correctAnswer: "A",
        solutionDetail: "[Co(en)3]3+ is chiral and shows optical isomerism.",
        solutionSteps: ["Recall chiral coordination complexes."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Coordination Compounds", "Chapter 9"],
        pyqYear: 2018,
      },
      {
        questionText: "IUPAC name of [Cr(H2O)6]Cl3 is:",
        options: makeOptions("Hexaaquachromium(III) chloride", "Trichlorohexaaquachromium", "Chromium(III) chloride hexahydrate", "Hexachlorochromium(III)"),
        correctAnswer: "A",
        solutionDetail: "The complex cation is hexaaquachromium(III) with chloride counter ions.",
        solutionSteps: ["Name cation first then anion."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Coordination Compounds", "Chapter 9"],
      },
      {
        questionText: "According to Werner, primary valence equals:",
        options: makeOptions("Oxidation state", "Coordination number", "Number of ligands", "Magnetic moment"),
        correctAnswer: "A",
        solutionDetail: "Primary valence corresponds to oxidation state of the metal.",
        solutionSteps: ["Recall Werner theory terms."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Coordination Compounds", "Chapter 9"],
        pyqYear: 2019,
      },
    ],
  },
  {
    chapterNumber: 10,
    topicName: "Haloalkanes and Haloarenes",
    questions: [
      {
        questionText: "Order of reactivity in SN1 reaction is:",
        options: makeOptions("Tertiary > secondary > primary", "Primary > secondary > tertiary", "Methyl > primary > tertiary", "Secondary > tertiary > primary"),
        correctAnswer: "A",
        solutionDetail: "SN1 is favored by stable carbocations, hence tertiary > secondary > primary.",
        solutionSteps: ["Recall SN1 mechanism and carbocation stability."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Haloalkanes and Haloarenes", "Chapter 10"],
      },
      {
        questionText: "Finkelstein reaction converts:",
        options: makeOptions("R-Cl to R-I using NaI in acetone", "R-I to R-Cl", "R-Br to R-F", "Aryl halides to alkyl halides"),
        correctAnswer: "A",
        solutionDetail: "Finkelstein reaction replaces Cl or Br with I using NaI in acetone.",
        solutionSteps: ["Recall Finkelstein reaction."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Haloalkanes and Haloarenes", "Chapter 10"],
        pyqYear: 2019,
      },
      {
        questionText: "Wurtz reaction is used for:",
        options: makeOptions("Coupling alkyl halides using sodium", "Reducing aldehydes", "Oxidizing alcohols", "Preparing alkenes"),
        correctAnswer: "A",
        solutionDetail: "Wurtz reaction couples alkyl halides with sodium in dry ether.",
        solutionSteps: ["Recall Wurtz reaction."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Haloalkanes and Haloarenes", "Chapter 10"],
      },
      {
        questionText: "Aryl halides are less reactive towards SN reactions due to:",
        options: makeOptions("Resonance and partial double bond character", "Higher polarity", "Lower bond strength only", "Steric effect only"),
        correctAnswer: "A",
        solutionDetail: "Resonance makes C-X bond in aryl halides stronger and less reactive.",
        solutionSteps: ["Recall resonance effects in aryl halides."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Haloalkanes and Haloarenes", "Chapter 10"],
      },
      {
        questionText: "Alcoholic KOH favors:",
        options: makeOptions("Elimination (alkene formation)", "Substitution only", "Addition reactions", "No reaction"),
        correctAnswer: "A",
        solutionDetail: "Alcoholic KOH promotes elimination to form alkenes.",
        solutionSteps: ["Recall effect of alcoholic KOH."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Haloalkanes and Haloarenes", "Chapter 10"],
      },
      {
        questionText: "Alkyl halides give precipitate with AgNO3 because:",
        options: makeOptions("They form AgX after ionization", "They are acidic", "They are basic", "They are insoluble always"),
        correctAnswer: "A",
        solutionDetail: "Alkyl halides ionize to give halide ions that form AgX precipitate.",
        solutionSteps: ["Recall AgNO3 test for alkyl halides."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Haloalkanes and Haloarenes", "Chapter 10"],
      },
    ],
  },
  {
    chapterNumber: 11,
    topicName: "Alcohols, Phenols and Ethers",
    questions: [
      {
        questionText: "Ethers are cleaved by HI to form:",
        options: makeOptions("Alkyl iodides and alcohols", "Aldehydes", "Ketones", "Carboxylic acids"),
        correctAnswer: "A",
        solutionDetail: "HI cleaves ethers to give alkyl iodide and alcohol.",
        solutionSteps: ["Recall cleavage of ethers."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Alcohols, Phenols and Ethers", "Chapter 11"],
      },
      {
        questionText: "Dehydration of alcohol with conc H2SO4 gives:",
        options: makeOptions("Alkene", "Alkane", "Carboxylic acid", "Ketone"),
        correctAnswer: "A",
        solutionDetail: "Concentrated H2SO4 dehydrates alcohols to alkenes.",
        solutionSteps: ["Recall dehydration reaction."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Alcohols, Phenols and Ethers", "Chapter 11"],
      },
      {
        questionText: "Reimer Tiemann reaction introduces:",
        options: makeOptions("CHO group on phenol", "NO2 group on phenol", "Cl group on phenol", "Br group on phenol"),
        correctAnswer: "A",
        solutionDetail: "Reimer Tiemann reaction formylates phenol to give salicylaldehyde.",
        solutionSteps: ["Recall Reimer Tiemann reaction."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Alcohols, Phenols and Ethers", "Chapter 11"],
        pyqYear: 2018,
      },
      {
        questionText: "Kolbe reaction of phenol gives:",
        options: makeOptions("Salicylic acid", "Benzene", "Aniline", "Toluene"),
        correctAnswer: "A",
        solutionDetail: "Kolbe Schmitt reaction gives salicylic acid from phenol.",
        solutionSteps: ["Recall Kolbe Schmitt reaction."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Alcohols, Phenols and Ethers", "Chapter 11"],
      },
      {
        questionText: "Alcohols can be oxidized to aldehydes by:",
        options: makeOptions("PCC", "NaBH4", "H2", "LiAlH4"),
        correctAnswer: "A",
        solutionDetail: "PCC oxidizes primary alcohols to aldehydes without over oxidation.",
        solutionSteps: ["Recall oxidation reagents."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Alcohols, Phenols and Ethers", "Chapter 11"],
      },
      {
        questionText: "Phenol undergoes electrophilic substitution mainly at:",
        options: makeOptions("Ortho and para positions", "Meta position", "Only para position", "Only ortho position"),
        correctAnswer: "A",
        solutionDetail: "The OH group activates ring and directs to ortho and para positions.",
        solutionSteps: ["Recall directing effect of OH group."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Alcohols, Phenols and Ethers", "Chapter 11"],
      },
    ],
  },
  {
    chapterNumber: 12,
    topicName: "Aldehydes, Ketones and Carboxylic Acids",
    questions: [
      {
        questionText: "Schiff's test is positive for:",
        options: makeOptions("Aldehydes", "Ketones", "Carboxylic acids", "Ethers"),
        correctAnswer: "A",
        solutionDetail: "Schiff reagent gives a pink color with aldehydes.",
        solutionSteps: ["Recall Schiff test."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Aldehydes, Ketones and Carboxylic Acids", "Chapter 12"],
      },
      {
        questionText: "Cannizzaro reaction is shown by:",
        options: makeOptions("Aldehydes without alpha hydrogen", "Aldehydes with alpha hydrogen", "Ketones only", "Carboxylic acids"),
        correctAnswer: "A",
        solutionDetail: "Cannizzaro reaction occurs for aldehydes lacking alpha hydrogen.",
        solutionSteps: ["Recall Cannizzaro conditions."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Aldehydes, Ketones and Carboxylic Acids", "Chapter 12"],
        pyqYear: 2019,
      },
      {
        questionText: "Aldehydes are more reactive than ketones because:",
        options: makeOptions("Less steric hindrance and weaker +I effect", "More steric hindrance", "No carbonyl group", "Greater stability"),
        correctAnswer: "A",
        solutionDetail: "Aldehydes have less steric hindrance and lower electron donation.",
        solutionSteps: ["Recall reactivity order of carbonyls."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Aldehydes, Ketones and Carboxylic Acids", "Chapter 12"],
      },
      {
        questionText: "Clemmensen reduction uses:",
        options: makeOptions("Zn-Hg/HCl", "NaBH4", "PCC", "KMnO4"),
        correctAnswer: "A",
        solutionDetail: "Clemmensen reduction uses Zn-Hg with HCl to reduce carbonyls.",
        solutionSteps: ["Recall reduction reagents."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Aldehydes, Ketones and Carboxylic Acids", "Chapter 12"],
        pyqYear: 2018,
      },
      {
        questionText: "Carboxylic acids are often dimeric due to:",
        options: makeOptions("Hydrogen bonding", "Ionic bonding", "Metallic bonding", "Covalent bonding only"),
        correctAnswer: "A",
        solutionDetail: "Carboxylic acids form dimers via hydrogen bonding.",
        solutionSteps: ["Recall structure of carboxylic acids."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Aldehydes, Ketones and Carboxylic Acids", "Chapter 12"],
      },
      {
        questionText: "LiAlH4 reduces carboxylic acids to:",
        options: makeOptions("Primary alcohols", "Aldehydes", "Ketones", "Alkenes"),
        correctAnswer: "A",
        solutionDetail: "LiAlH4 reduces carboxylic acids to primary alcohols.",
        solutionSteps: ["Recall reducing agents."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Aldehydes, Ketones and Carboxylic Acids", "Chapter 12"],
      },
    ],
  },
  {
    chapterNumber: 13,
    topicName: "Amines",
    questions: [
      {
        questionText: "Basicity of aliphatic amines in aqueous solution follows:",
        options: makeOptions("Secondary > primary > tertiary > ammonia", "Primary > secondary > tertiary > ammonia", "Tertiary > secondary > primary > ammonia", "Ammonia > tertiary > secondary > primary"),
        correctAnswer: "A",
        solutionDetail: "Secondary amines are most basic in aqueous solution due to solvation and +I effect.",
        solutionSteps: ["Recall basicity order in aqueous medium."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Amines", "Chapter 13"],
      },
      {
        questionText: "Hinsberg test is used to distinguish:",
        options: makeOptions("Primary, secondary, tertiary amines", "Aldehydes and ketones", "Alcohols and phenols", "Carboxylic acids"),
        correctAnswer: "A",
        solutionDetail: "Hinsberg test differentiates amines based on sulfonamide formation.",
        solutionSteps: ["Recall purpose of Hinsberg test."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Amines", "Chapter 13"],
      },
      {
        questionText: "Aniline is less basic than aliphatic amines because:",
        options: makeOptions("Lone pair is delocalized by resonance", "It has higher molecular mass", "It is a tertiary amine", "It is ionic"),
        correctAnswer: "A",
        solutionDetail: "Resonance delocalizes the lone pair, reducing basicity.",
        solutionSteps: ["Recall resonance effect on basicity."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Amines", "Chapter 13"],
      },
      {
        questionText: "Diazonium salts are used in:",
        options: makeOptions("Azo dye formation", "Grignard reaction", "Aldol condensation", "Polymerization"),
        correctAnswer: "A",
        solutionDetail: "Diazonium salts undergo coupling to form azo dyes.",
        solutionSteps: ["Recall application of diazonium salts."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Amines", "Chapter 13"],
        pyqYear: 2020,
      },
      {
        questionText: "Hoffmann bromamide reaction gives:",
        options: makeOptions("Amine with one carbon less", "Amide with one carbon more", "Alcohol", "Ketone"),
        correctAnswer: "A",
        solutionDetail: "Hoffmann bromamide reduces carbon chain by one.",
        solutionSteps: ["Recall Hoffmann bromamide reaction."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Amines", "Chapter 13"],
      },
      {
        questionText: "Primary aliphatic amines react with nitrous acid to give:",
        options: makeOptions("Alcohol and nitrogen gas", "Diazonium salt", "Amide", "Azo dye"),
        correctAnswer: "A",
        solutionDetail: "Primary aliphatic amines form alcohols with evolution of nitrogen.",
        solutionSteps: ["Recall nitrous acid reaction."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Amines", "Chapter 13"],
        pyqYear: 2018,
      },
    ],
  },
  {
    chapterNumber: 14,
    topicName: "Biomolecules",
    questions: [
      {
        questionText: "Glucose is classified as:",
        options: makeOptions("Aldohexose", "Ketohexose", "Aldopentose", "Ketopentose"),
        correctAnswer: "A",
        solutionDetail: "Glucose is an aldohexose with six carbon atoms.",
        solutionSteps: ["Recall classification of glucose."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biomolecules", "Chapter 14"],
      },
      {
        questionText: "Cellulose contains:",
        options: makeOptions("Beta 1,4 glycosidic linkage", "Alpha 1,4 linkage", "Alpha 1,6 linkage", "Beta 1,6 linkage"),
        correctAnswer: "A",
        solutionDetail: "Cellulose is made of beta 1,4 linked glucose units.",
        solutionSteps: ["Recall structure of cellulose."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Biomolecules", "Chapter 14"],
      },
      {
        questionText: "Essential amino acids are those that:",
        options: makeOptions("Cannot be synthesized by the body", "Are synthesized by liver", "Contain sulfur", "Are acidic"),
        correctAnswer: "A",
        solutionDetail: "Essential amino acids must be obtained from diet.",
        solutionSteps: ["Recall essential amino acids."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biomolecules", "Chapter 14"],
      },
      {
        questionText: "DNA contains:",
        options: makeOptions("Deoxyribose sugar", "Ribose sugar", "Glucose", "Fructose"),
        correctAnswer: "A",
        solutionDetail: "DNA contains deoxyribose while RNA contains ribose.",
        solutionSteps: ["Recall sugars in nucleic acids."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biomolecules", "Chapter 14"],
      },
      {
        questionText: "Vitamin B1 deficiency causes:",
        options: makeOptions("Beriberi", "Scurvy", "Rickets", "Night blindness"),
        correctAnswer: "A",
        solutionDetail: "Deficiency of vitamin B1 leads to beriberi.",
        solutionSteps: ["Recall vitamin deficiency diseases."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Biomolecules", "Chapter 14"],
        pyqYear: 2019,
      },
      {
        questionText: "The simplest amino acid is:",
        options: makeOptions("Glycine", "Alanine", "Valine", "Serine"),
        correctAnswer: "A",
        solutionDetail: "Glycine has H as side chain and is the simplest amino acid.",
        solutionSteps: ["Recall amino acid structures."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biomolecules", "Chapter 14"],
      },
    ],
  },
  {
    chapterNumber: 15,
    topicName: "Polymers",
    questions: [
      {
        questionText: "Monomer of PVC is:",
        options: makeOptions("Vinyl chloride", "Vinyl acetate", "Styrene", "Ethylene"),
        correctAnswer: "A",
        solutionDetail: "PVC is polyvinyl chloride, formed from vinyl chloride monomer.",
        solutionSteps: ["Recall monomer of PVC."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Polymers", "Chapter 15"],
      },
      {
        questionText: "Bakelite is a:",
        options: makeOptions("Thermosetting polymer", "Thermoplastic polymer", "Elastomer", "Natural polymer"),
        correctAnswer: "A",
        solutionDetail: "Bakelite is a thermosetting phenol formaldehyde polymer.",
        solutionSteps: ["Recall types of polymers."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Polymers", "Chapter 15"],
      },
      {
        questionText: "Vulcanization of rubber uses:",
        options: makeOptions("Sulfur", "Chlorine", "Nitrogen", "Oxygen"),
        correctAnswer: "A",
        solutionDetail: "Sulfur cross links improve elasticity and strength.",
        solutionSteps: ["Recall vulcanization process."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Polymers", "Chapter 15"],
        pyqYear: 2020,
      },
      {
        questionText: "Teflon is:",
        options: makeOptions("Polytetrafluoroethylene", "Polyvinyl chloride", "Polystyrene", "Polyacrylonitrile"),
        correctAnswer: "A",
        solutionDetail: "Teflon is polytetrafluoroethylene (PTFE).",
        solutionSteps: ["Recall common polymer names."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Polymers", "Chapter 15"],
      },
      {
        questionText: "Neoprene is a polymer of:",
        options: makeOptions("Chloroprene", "Isoprene", "Butadiene", "Styrene"),
        correctAnswer: "A",
        solutionDetail: "Neoprene is polymerized chloroprene.",
        solutionSteps: ["Recall monomers of synthetic rubbers."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Polymers", "Chapter 15"],
      },
      {
        questionText: "Nylon 6,6 is formed from:",
        options: makeOptions("Hexamethylenediamine and adipic acid", "Caprolactam", "Ethylene glycol and terephthalic acid", "Styrene"),
        correctAnswer: "A",
        solutionDetail: "Nylon 6,6 is formed from hexamethylenediamine and adipic acid.",
        solutionSteps: ["Recall monomers of nylon 6,6."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Polymers", "Chapter 15"],
      },
    ],
  },
  {
    chapterNumber: 16,
    topicName: "Chemistry in Everyday Life",
    questions: [
      {
        questionText: "Antipyretics are drugs used to:",
        options: makeOptions("Reduce fever", "Relieve pain", "Treat infections", "Induce sleep"),
        correctAnswer: "A",
        solutionDetail: "Antipyretics reduce fever by lowering body temperature.",
        solutionSteps: ["Recall drug categories."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Chemistry in Everyday Life", "Chapter 16"],
      },
      {
        questionText: "Antibiotics are effective against:",
        options: makeOptions("Bacteria", "Viruses", "Fungi only", "All pathogens"),
        correctAnswer: "A",
        solutionDetail: "Antibiotics target bacterial infections, not viruses.",
        solutionSteps: ["Recall antibiotic action."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Chemistry in Everyday Life", "Chapter 16"],
      },
      {
        questionText: "Antacids are used to:",
        options: makeOptions("Neutralize excess stomach acid", "Increase acidity", "Treat allergies", "Act as sedatives"),
        correctAnswer: "A",
        solutionDetail: "Antacids neutralize excess hydrochloric acid in stomach.",
        solutionSteps: ["Recall use of antacids."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Chemistry in Everyday Life", "Chapter 16"],
      },
      {
        questionText: "Sodium benzoate is used as a:",
        options: makeOptions("Preservative in acidic foods", "Analgesic", "Antacid", "Antibiotic"),
        correctAnswer: "A",
        solutionDetail: "Sodium benzoate preserves acidic foods like juices.",
        solutionSteps: ["Recall food preservatives."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Chemistry in Everyday Life", "Chapter 16"],
        pyqYear: 2018,
      },
      {
        questionText: "Detergents are sodium salts of:",
        options: makeOptions("Sulfonated long chain hydrocarbons", "Carboxylic acids", "Amino acids", "Alcohols"),
        correctAnswer: "A",
        solutionDetail: "Detergents are sodium salts of sulfonated long chain hydrocarbons.",
        solutionSteps: ["Recall composition of detergents."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Chemistry in Everyday Life", "Chapter 16"],
      },
      {
        questionText: "Tranquilizers are drugs that:",
        options: makeOptions("Reduce anxiety by acting on CNS", "Increase appetite", "Act as antibiotics", "Cure infections"),
        correctAnswer: "A",
        solutionDetail: "Tranquilizers act on the CNS to reduce anxiety and stress.",
        solutionSteps: ["Recall use of tranquilizers."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Chemistry in Everyday Life", "Chapter 16"],
        pyqYear: 2021,
      },
    ],
  },
];

async function ensureTopicId(topicName: string, chapterNumber: number) {
  const existing = await db
    .select({ id: contentTopics.id })
    .from(contentTopics)
    .where(
      and(
        eq(contentTopics.subject, "Chemistry"),
        eq(contentTopics.classLevel, "12"),
        eq(contentTopics.topicName, topicName)
      )
    )
    .limit(1);

  if (existing.length > 0) {
    return existing[0].id;
  }

  const inserted = await db
    .insert(contentTopics)
    .values({
      subject: "Chemistry",
      classLevel: "12",
      topicName,
      ncertChapter: `Chapter ${chapterNumber}`,
      referenceBooks: ["NCERT Chemistry"],
    })
    .returning({ id: contentTopics.id });

  return inserted[0].id;
}

async function seedChemistryClass12QuestionsTopup() {
  console.log("Seeding Chemistry Class 12 additional practice questions...");
  const targetPerChapter = 10;

  for (const chapter of chapters) {
    const topicId = await ensureTopicId(chapter.topicName, chapter.chapterNumber);
    const countResult = await db
      .select({ count: sql<number>`count(*)` })
      .from(questions)
      .where(eq(questions.topicId, topicId));
    const existingCount = Number(countResult[0]?.count ?? 0);

    if (existingCount >= targetPerChapter) {
      console.log(`  Chapter ${chapter.chapterNumber}: already has ${existingCount} questions, skipping`);
      continue;
    }

    const remaining = Math.max(targetPerChapter - existingCount, 0);
    if (remaining > chapter.questions.length) {
      console.warn(
        `  Chapter ${chapter.chapterNumber}: only ${chapter.questions.length} extra questions available for ${remaining} slots`
      );
    }

    const payload = chapter.questions.slice(0, remaining).map((question) => ({
      topicId,
      questionText: question.questionText,
      options: question.options,
      correctAnswer: question.correctAnswer,
      solutionDetail: question.solutionDetail,
      solutionSteps: question.solutionSteps ?? [],
      difficultyLevel: question.difficultyLevel,
      sourceType: question.sourceType,
      relatedTopics: question.relatedTopics,
      pyqYear: question.pyqYear ?? null,
    }));

    if (payload.length === 0) {
      console.log(`  Chapter ${chapter.chapterNumber}: no new questions to insert`);
      continue;
    }

    await db.insert(questions).values(payload);
    console.log(`  Chapter ${chapter.chapterNumber}: inserted ${payload.length} questions`);
  }

  console.log("Chemistry Class 12 additional questions seeding completed!");
}

seedChemistryClass12QuestionsTopup().catch((error) => {
  console.error("Failed to seed Chemistry Class 12 questions:", error);
});
