import { db } from "../db";
import { contentTopics, questions } from "../../shared/schema";
import { and, eq, sql } from "drizzle-orm";

type QuestionSeed = {
  questionText: string;
  options: { id: string; text: string }[];
  correctAnswer: string;
  solutionDetail: string;
  solutionSteps?: string[];
  difficultyLevel: number;
  sourceType: string;
  relatedTopics: string[];
  pyqYear?: number | null;
};

type ChapterSeed = {
  chapterNumber: number;
  topicName: string;
  questions: QuestionSeed[];
};

const makeOptions = (a: string, b: string, c: string, d: string) => [
  { id: "A", text: a },
  { id: "B", text: b },
  { id: "C", text: c },
  { id: "D", text: d },
];

const chapters: ChapterSeed[] = [
  {
    chapterNumber: 1,
    topicName: "Reproduction in Organisms",
    questions: [
      {
        questionText: "Asexual reproduction generally produces offspring that are:",
        options: makeOptions(
          "Genetically identical to the parent",
          "Genetically diverse",
          "Always polyploid",
          "Produced only by meiosis"
        ),
        correctAnswer: "A",
        solutionDetail: "Asexual reproduction involves mitosis and produces clones.",
        solutionSteps: ["Recall the definition of asexual reproduction."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Reproduction in Organisms", "Chapter 1"],
      },
      {
        questionText: "Budding is a common mode of reproduction in:",
        options: makeOptions("Hydra", "Amoeba", "Plasmodium", "Spirogyra"),
        correctAnswer: "A",
        solutionDetail: "Hydra reproduces asexually by budding.",
        solutionSteps: ["Identify the organism that shows budding."],
        difficultyLevel: 1,
        sourceType: "pyq",
        relatedTopics: ["Reproduction in Organisms", "Chapter 1"],
        pyqYear: 2017,
      },
      {
        questionText: "The term clone refers to:",
        options: makeOptions(
          "Genetically identical individuals",
          "Only plants produced by seeds",
          "Hybrid offspring only",
          "Offspring with different chromosome number"
        ),
        correctAnswer: "A",
        solutionDetail: "Clones are genetically identical individuals.",
        solutionSteps: ["Recall the meaning of clone."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Reproduction in Organisms", "Chapter 1"],
      },
      {
        questionText: "An organism that reproduces only once in its lifetime is called:",
        options: makeOptions("Semelparous", "Iteroparous", "Viviparous", "Ovoviviparous"),
        correctAnswer: "A",
        solutionDetail: "Semelparous organisms reproduce only once.",
        solutionSteps: ["Recall the term for single reproductive event."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Reproduction in Organisms", "Chapter 1"],
      },
      {
        questionText: "Fragmentation as a mode of reproduction is common in:",
        options: makeOptions("Spirogyra", "Frog", "Hydra", "Planaria"),
        correctAnswer: "A",
        solutionDetail: "Spirogyra reproduces by fragmentation.",
        solutionSteps: ["Identify the organism that shows fragmentation."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Reproduction in Organisms", "Chapter 1"],
      },
      {
        questionText: "Sexual reproduction is characterized by:",
        options: makeOptions(
          "Fusion of gametes and genetic variation",
          "No gamete formation",
          "Offspring identical to parent",
          "Only mitotic divisions"
        ),
        correctAnswer: "A",
        solutionDetail: "Sexual reproduction involves gamete fusion and variation.",
        solutionSteps: ["Recall the key feature of sexual reproduction."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Reproduction in Organisms", "Chapter 1"],
      },
      {
        questionText: "In honeybee, parthenogenesis produces:",
        options: makeOptions("Drones (males)", "Queen only", "Workers only", "Both sexes equally"),
        correctAnswer: "A",
        solutionDetail: "Unfertilized eggs develop into male drones.",
        solutionSteps: ["Recall the outcome of parthenogenesis in honeybee."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Reproduction in Organisms", "Chapter 1"],
        pyqYear: 2018,
      },
      {
        questionText: "Juvenile phase in animals refers to the period between:",
        options: makeOptions(
          "Birth and reproductive maturity",
          "Fertilization and birth",
          "Old age and death",
          "Reproductive maturity and death"
        ),
        correctAnswer: "A",
        solutionDetail: "Juvenile phase is the time before reproductive maturity.",
        solutionSteps: ["Recall definition of juvenile phase."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Reproduction in Organisms", "Chapter 1"],
      },
    ],
  },
  {
    chapterNumber: 2,
    topicName: "Sexual Reproduction in Flowering Plants",
    questions: [
      {
        questionText: "The male gametophyte in angiosperms is the:",
        options: makeOptions("Pollen grain", "Embryo sac", "Ovule", "Endosperm"),
        correctAnswer: "A",
        solutionDetail: "Pollen grain represents the male gametophyte.",
        solutionSteps: ["Recall the identity of male gametophyte."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Sexual Reproduction in Flowering Plants", "Chapter 2"],
      },
      {
        questionText: "The functional megaspore develops into the:",
        options: makeOptions("Embryo sac", "Pollen tube", "Endosperm", "Seed coat"),
        correctAnswer: "A",
        solutionDetail: "The functional megaspore forms the embryo sac.",
        solutionSteps: ["Recall development of the megaspore."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Sexual Reproduction in Flowering Plants", "Chapter 2"],
      },
      {
        questionText: "Double fertilization results in formation of:",
        options: makeOptions("Zygote and endosperm", "Two zygotes", "Embryo and seed coat", "Two embryos"),
        correctAnswer: "A",
        solutionDetail: "One male gamete forms the zygote and the other forms endosperm.",
        solutionSteps: ["Recall the outcome of double fertilization."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Sexual Reproduction in Flowering Plants", "Chapter 2"],
        pyqYear: 2018,
      },
      {
        questionText: "A typical mature embryo sac in angiosperms is:",
        options: makeOptions("7 celled and 8 nucleate", "8 celled and 7 nucleate", "4 celled and 4 nucleate", "10 celled and 8 nucleate"),
        correctAnswer: "A",
        solutionDetail: "The mature embryo sac has 7 cells and 8 nuclei.",
        solutionSteps: ["Recall the structure of embryo sac."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Sexual Reproduction in Flowering Plants", "Chapter 2"],
        pyqYear: 2020,
      },
      {
        questionText: "Placentation refers to the arrangement of:",
        options: makeOptions("Ovules in the ovary", "Pollen grains in anther", "Sepals in flower", "Petals in flower"),
        correctAnswer: "A",
        solutionDetail: "Placentation is the arrangement of ovules in the ovary.",
        solutionSteps: ["Recall the definition of placentation."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Sexual Reproduction in Flowering Plants", "Chapter 2"],
      },
      {
        questionText: "Apomixis is the formation of seed:",
        options: makeOptions("Without fertilization", "After double fertilization", "Only in gymnosperms", "By fusion of gametes"),
        correctAnswer: "A",
        solutionDetail: "Apomixis produces seeds without fertilization.",
        solutionSteps: ["Recall the meaning of apomixis."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Sexual Reproduction in Flowering Plants", "Chapter 2"],
      },
      {
        questionText: "Polyembryony means:",
        options: makeOptions("More than one embryo in a seed", "One embryo in many seeds", "Embryo without endosperm", "Seed without embryo"),
        correctAnswer: "A",
        solutionDetail: "Polyembryony is formation of more than one embryo in a seed.",
        solutionSteps: ["Recall the definition of polyembryony."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Sexual Reproduction in Flowering Plants", "Chapter 2"],
        pyqYear: 2017,
      },
      {
        questionText: "The generative cell of pollen divides to form:",
        options: makeOptions("Two male gametes", "One male gamete", "Two synergids", "Egg and polar nuclei"),
        correctAnswer: "A",
        solutionDetail: "Generative cell divides to form two male gametes.",
        solutionSteps: ["Recall division of generative cell."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Sexual Reproduction in Flowering Plants", "Chapter 2"],
      },
    ],
  },
  {
    chapterNumber: 3,
    topicName: "Human Reproduction",
    questions: [
      {
        questionText: "Spermatogenesis occurs in the:",
        options: makeOptions("Seminiferous tubules", "Epididymis", "Vas deferens", "Prostate gland"),
        correctAnswer: "A",
        solutionDetail: "Spermatogenesis takes place in seminiferous tubules.",
        solutionSteps: ["Recall the site of spermatogenesis."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Human Reproduction", "Chapter 3"],
      },
      {
        questionText: "The acrosome of sperm is derived from the:",
        options: makeOptions("Golgi apparatus", "Mitochondria", "Nucleus", "Endoplasmic reticulum"),
        correctAnswer: "A",
        solutionDetail: "The acrosome is formed from Golgi apparatus.",
        solutionSteps: ["Recall origin of acrosome."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Human Reproduction", "Chapter 3"],
      },
      {
        questionText: "The hormone that maintains corpus luteum in early pregnancy is:",
        options: makeOptions("hCG", "FSH", "Oxytocin", "TSH"),
        correctAnswer: "A",
        solutionDetail: "hCG maintains the corpus luteum in early pregnancy.",
        solutionSteps: ["Recall the role of hCG."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Human Reproduction", "Chapter 3"],
      },
      {
        questionText: "Placenta is formed by:",
        options: makeOptions("Chorion and endometrium", "Amnion and chorion", "Uterus only", "Ovary and uterus"),
        correctAnswer: "A",
        solutionDetail: "Placenta forms from fetal chorion and maternal endometrium.",
        solutionSteps: ["Recall placental origin."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Human Reproduction", "Chapter 3"],
      },
      {
        questionText: "Fructose in seminal fluid is secreted by the:",
        options: makeOptions("Seminal vesicles", "Prostate gland", "Bulbourethral gland", "Testes"),
        correctAnswer: "A",
        solutionDetail: "Seminal vesicles provide fructose for sperm energy.",
        solutionSteps: ["Recall composition of seminal plasma."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Human Reproduction", "Chapter 3"],
        pyqYear: 2019,
      },
      {
        questionText: "Capacitation of sperm refers to:",
        options: makeOptions("Functional maturation in female tract", "Formation of acrosome", "Fusion of gametes", "Sperm production"),
        correctAnswer: "A",
        solutionDetail: "Capacitation is functional maturation of sperm in female tract.",
        solutionSteps: ["Recall the meaning of capacitation."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Human Reproduction", "Chapter 3"],
      },
      {
        questionText: "The hormone responsible for milk ejection is:",
        options: makeOptions("Oxytocin", "Prolactin", "FSH", "LH"),
        correctAnswer: "A",
        solutionDetail: "Oxytocin causes milk ejection from mammary glands.",
        solutionSteps: ["Recall hormone functions in lactation."],
        difficultyLevel: 1,
        sourceType: "pyq",
        relatedTopics: ["Human Reproduction", "Chapter 3"],
        pyqYear: 2020,
      },
      {
        questionText: "Implantation of the blastocyst occurs in the:",
        options: makeOptions("Endometrium of uterus", "Ovary", "Cervix", "Vagina"),
        correctAnswer: "A",
        solutionDetail: "Implantation occurs in the endometrium.",
        solutionSteps: ["Recall the site of implantation."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Human Reproduction", "Chapter 3"],
      },
    ],
  },
  {
    chapterNumber: 4,
    topicName: "Reproductive Health",
    questions: [
      {
        questionText: "Barrier method of contraception includes:",
        options: makeOptions("Condoms", "Oral pills", "Copper T", "Vasectomy"),
        correctAnswer: "A",
        solutionDetail: "Condoms prevent sperm entry and are barrier methods.",
        solutionSteps: ["Identify a barrier method."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Reproductive Health", "Chapter 4"],
      },
      {
        questionText: "Copper releasing IUDs mainly act by:",
        options: makeOptions(
          "Increasing phagocytosis of sperms",
          "Blocking ovulation",
          "Destroying embryos",
          "Stopping menstruation"
        ),
        correctAnswer: "A",
        solutionDetail: "Copper IUDs reduce sperm motility and increase phagocytosis.",
        solutionSteps: ["Recall action of copper IUDs."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Reproductive Health", "Chapter 4"],
      },
      {
        questionText: "Saheli is a contraceptive pill containing:",
        options: makeOptions("Centchroman", "Progesterone only", "Testosterone", "Estrogen only"),
        correctAnswer: "A",
        solutionDetail: "Saheli is a non steroidal pill containing centchroman.",
        solutionSteps: ["Recall composition of Saheli."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Reproductive Health", "Chapter 4"],
      },
      {
        questionText: "IVF-ET refers to:",
        options: makeOptions(
          "Fertilization outside body followed by embryo transfer",
          "Gametes placed in fallopian tube",
          "Direct injection of sperm into ovum",
          "Artificial insemination"
        ),
        correctAnswer: "A",
        solutionDetail: "IVF-ET is in vitro fertilization followed by embryo transfer.",
        solutionSteps: ["Recall the full form of IVF-ET."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Reproductive Health", "Chapter 4"],
        pyqYear: 2019,
      },
      {
        questionText: "GIFT stands for:",
        options: makeOptions(
          "Gamete intrafallopian transfer",
          "Genetic intrauterine fertilization technique",
          "Gamete induced fertilization transfer",
          "Gonad intrafallopian transfer"
        ),
        correctAnswer: "A",
        solutionDetail: "GIFT stands for Gamete IntraFallopian Transfer.",
        solutionSteps: ["Recall assisted reproductive techniques."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Reproductive Health", "Chapter 4"],
        pyqYear: 2018,
      },
      {
        questionText: "Amniocentesis is used for:",
        options: makeOptions(
          "Prenatal diagnosis of genetic disorders",
          "Delivery of baby",
          "Removal of ovum",
          "Contraception"
        ),
        correctAnswer: "A",
        solutionDetail: "Amniocentesis helps detect genetic abnormalities before birth.",
        solutionSteps: ["Recall the purpose of amniocentesis."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Reproductive Health", "Chapter 4"],
      },
      {
        questionText: "Use of condoms helps prevent:",
        options: makeOptions(
          "Pregnancy and STDs",
          "Ovulation",
          "Menstrual cycle",
          "Implantation"
        ),
        correctAnswer: "A",
        solutionDetail: "Condoms act as barrier and reduce STD transmission.",
        solutionSteps: ["Recall advantages of condoms."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Reproductive Health", "Chapter 4"],
      },
      {
        questionText: "Vasectomy involves cutting and tying the:",
        options: makeOptions("Vas deferens", "Urethra", "Testis", "Prostate gland"),
        correctAnswer: "A",
        solutionDetail: "Vasectomy blocks the vas deferens to prevent sperm transport.",
        solutionSteps: ["Recall the surgical male contraception method."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Reproductive Health", "Chapter 4"],
      },
    ],
  },
  {
    chapterNumber: 5,
    topicName: "Principles of Inheritance and Variation",
    questions: [
      {
        questionText: "Phenotypic ratio in F2 generation of a monohybrid cross is:",
        options: makeOptions("3:1", "1:2:1", "9:3:3:1", "2:1"),
        correctAnswer: "A",
        solutionDetail: "Monohybrid F2 phenotypic ratio is 3:1.",
        solutionSteps: ["Recall Mendelian monohybrid ratio."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Principles of Inheritance and Variation", "Chapter 5"],
      },
      {
        questionText: "A test cross is performed between a heterozygote and a:",
        options: makeOptions("Homozygous recessive", "Homozygous dominant", "Another heterozygote", "Mutant"),
        correctAnswer: "A",
        solutionDetail: "Test cross uses a homozygous recessive to reveal genotype.",
        solutionSteps: ["Recall definition of test cross."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Principles of Inheritance and Variation", "Chapter 5"],
      },
      {
        questionText: "Incomplete dominance is illustrated by:",
        options: makeOptions("Snapdragon flower color", "ABO blood group", "Mendel pea seed shape", "Sex linked inheritance"),
        correctAnswer: "A",
        solutionDetail: "Snapdragon shows intermediate phenotype in F1 generation.",
        solutionSteps: ["Recall classic example of incomplete dominance."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Principles of Inheritance and Variation", "Chapter 5"],
        pyqYear: 2018,
      },
      {
        questionText: "ABO blood group inheritance shows:",
        options: makeOptions("Codominance", "Incomplete dominance", "Linkage", "Epistasis"),
        correctAnswer: "A",
        solutionDetail: "IA and IB alleles are codominant.",
        solutionSteps: ["Recall ABO blood group genetics."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Principles of Inheritance and Variation", "Chapter 5"],
        pyqYear: 2020,
      },
      {
        questionText: "Recombination frequency of 50 percent indicates:",
        options: makeOptions(
          "Independent assortment of genes",
          "Complete linkage",
          "Genes on same locus",
          "No crossing over"
        ),
        correctAnswer: "A",
        solutionDetail: "50 percent recombination implies independent assortment.",
        solutionSteps: ["Recall interpretation of recombination frequency."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Principles of Inheritance and Variation", "Chapter 5"],
      },
      {
        questionText: "Turner syndrome karyotype is:",
        options: makeOptions("45,X", "47,XXY", "47,XXX", "46,XY"),
        correctAnswer: "A",
        solutionDetail: "Turner syndrome has monosomy X (45,X).",
        solutionSteps: ["Recall chromosomal disorders."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Principles of Inheritance and Variation", "Chapter 5"],
      },
      {
        questionText: "Klinefelter syndrome karyotype is:",
        options: makeOptions("47,XXY", "45,X", "47,XXX", "46,XX"),
        correctAnswer: "A",
        solutionDetail: "Klinefelter syndrome is 47,XXY.",
        solutionSteps: ["Recall chromosomal disorders."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Principles of Inheritance and Variation", "Chapter 5"],
      },
      {
        questionText: "Hemophilia is a:",
        options: makeOptions("Sex linked recessive disorder", "Autosomal dominant disorder", "Mitochondrial disorder", "Chromosomal deletion"),
        correctAnswer: "A",
        solutionDetail: "Hemophilia is an X linked recessive disorder.",
        solutionSteps: ["Recall inheritance of hemophilia."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Principles of Inheritance and Variation", "Chapter 5"],
        pyqYear: 2019,
      },
    ],
  },
  {
    chapterNumber: 6,
    topicName: "Molecular Basis of Inheritance",
    questions: [
      {
        questionText: "A pairs with T in DNA through:",
        options: makeOptions("Two hydrogen bonds", "Three hydrogen bonds", "Ionic bonds", "Peptide bonds"),
        correctAnswer: "A",
        solutionDetail: "Adenine pairs with thymine via two hydrogen bonds.",
        solutionSteps: ["Recall base pairing rules."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Molecular Basis of Inheritance", "Chapter 6"],
      },
      {
        questionText: "Okazaki fragments are synthesized on the:",
        options: makeOptions("Lagging strand", "Leading strand", "Template strand only", "Coding strand only"),
        correctAnswer: "A",
        solutionDetail: "Lagging strand is synthesized discontinuously as Okazaki fragments.",
        solutionSteps: ["Recall DNA replication strands."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Molecular Basis of Inheritance", "Chapter 6"],
      },
      {
        questionText: "Enzyme that joins Okazaki fragments is:",
        options: makeOptions("DNA ligase", "DNA polymerase", "Helicase", "Primase"),
        correctAnswer: "A",
        solutionDetail: "DNA ligase seals the nicks between fragments.",
        solutionSteps: ["Recall enzymes of replication."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Molecular Basis of Inheritance", "Chapter 6"],
      },
      {
        questionText: "The start codon in mRNA is:",
        options: makeOptions("AUG", "UAA", "UGA", "UAG"),
        correctAnswer: "A",
        solutionDetail: "AUG codes for methionine and initiates translation.",
        solutionSteps: ["Recall start codon."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Molecular Basis of Inheritance", "Chapter 6"],
      },
      {
        questionText: "Operon model of gene regulation was proposed by:",
        options: makeOptions("Jacob and Monod", "Watson and Crick", "Hershey and Chase", "Meselson and Stahl"),
        correctAnswer: "A",
        solutionDetail: "Jacob and Monod proposed the operon model in bacteria.",
        solutionSteps: ["Recall operon model scientists."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Molecular Basis of Inheritance", "Chapter 6"],
        pyqYear: 2018,
      },
      {
        questionText: "The inducer of lac operon is:",
        options: makeOptions("Allolactose", "Glucose", "Galactose", "Lactase enzyme"),
        correctAnswer: "A",
        solutionDetail: "Allolactose binds the repressor and induces lac operon.",
        solutionSteps: ["Recall lac operon regulation."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Molecular Basis of Inheritance", "Chapter 6"],
      },
      {
        questionText: "DNA synthesis proceeds in the:",
        options: makeOptions("5 to 3 direction", "3 to 5 direction", "Both directions", "Random direction"),
        correctAnswer: "A",
        solutionDetail: "DNA polymerase adds nucleotides in 5 to 3 direction.",
        solutionSteps: ["Recall direction of DNA synthesis."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Molecular Basis of Inheritance", "Chapter 6"],
      },
      {
        questionText: "Reverse transcriptase synthesizes:",
        options: makeOptions("DNA from RNA", "RNA from DNA", "Protein from RNA", "DNA from protein"),
        correctAnswer: "A",
        solutionDetail: "Reverse transcriptase uses RNA as template to make DNA.",
        solutionSteps: ["Recall role of reverse transcriptase."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Molecular Basis of Inheritance", "Chapter 6"],
        pyqYear: 2021,
      },
    ],
  },
  {
    chapterNumber: 7,
    topicName: "Evolution",
    questions: [
      {
        questionText: "Homologous organs indicate:",
        options: makeOptions("Common ancestry", "Convergent evolution", "No relation", "Same function only"),
        correctAnswer: "A",
        solutionDetail: "Homologous organs indicate common ancestry and divergent evolution.",
        solutionSteps: ["Recall evidence of evolution."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Evolution", "Chapter 7"],
      },
      {
        questionText: "Analogous organs indicate:",
        options: makeOptions("Convergent evolution", "Divergent evolution", "Common ancestry only", "No evolution"),
        correctAnswer: "A",
        solutionDetail: "Analogous organs arise due to convergent evolution.",
        solutionSteps: ["Recall analogous organs."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Evolution", "Chapter 7"],
      },
      {
        questionText: "Industrial melanism in peppered moth is an example of:",
        options: makeOptions("Natural selection", "Genetic drift", "Mutation only", "Hybridization"),
        correctAnswer: "A",
        solutionDetail: "Industrial melanism illustrates natural selection.",
        solutionSteps: ["Recall classic selection example."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Evolution", "Chapter 7"],
      },
      {
        questionText: "Hardy-Weinberg equilibrium is expressed as:",
        options: makeOptions("p^2 + 2pq + q^2 = 1", "p + q = 1", "p^2 + q^2 = 1", "p^2 - 2pq + q^2 = 1"),
        correctAnswer: "A",
        solutionDetail: "Hardy-Weinberg equilibrium is p^2 + 2pq + q^2 = 1.",
        solutionSteps: ["Recall Hardy-Weinberg equation."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Evolution", "Chapter 7"],
        pyqYear: 2019,
      },
      {
        questionText: "Allopatric speciation occurs due to:",
        options: makeOptions("Geographic isolation", "Polyploidy", "Hybridization", "Artificial selection"),
        correctAnswer: "A",
        solutionDetail: "Geographic isolation separates populations leading to allopatric speciation.",
        solutionSteps: ["Recall types of speciation."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Evolution", "Chapter 7"],
      },
      {
        questionText: "Adaptive radiation is illustrated by:",
        options: makeOptions("Darwin's finches", "Homo sapiens", "Industrial melanism", "Sickle cell anemia"),
        correctAnswer: "A",
        solutionDetail: "Darwin's finches are a classic example of adaptive radiation.",
        solutionSteps: ["Recall adaptive radiation examples."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Evolution", "Chapter 7"],
        pyqYear: 2020,
      },
      {
        questionText: "Use and disuse theory was proposed by:",
        options: makeOptions("Lamarck", "Darwin", "Wallace", "Mendel"),
        correctAnswer: "A",
        solutionDetail: "Lamarck proposed the theory of use and disuse.",
        solutionSteps: ["Recall evolution theories."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Evolution", "Chapter 7"],
      },
      {
        questionText: "Genetic drift is most significant in:",
        options: makeOptions("Small populations", "Large populations", "Stable populations", "Hybrid populations"),
        correctAnswer: "A",
        solutionDetail: "Random changes are more significant in small populations.",
        solutionSteps: ["Recall genetic drift effects."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Evolution", "Chapter 7"],
      },
    ],
  },
  {
    chapterNumber: 8,
    topicName: "Human Health and Disease",
    questions: [
      {
        questionText: "Antibodies are produced by:",
        options: makeOptions("Plasma cells", "T cells", "Macrophages", "Neutrophils"),
        correctAnswer: "A",
        solutionDetail: "Plasma cells are antibody secreting B cells.",
        solutionSteps: ["Recall antibody producing cells."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Human Health and Disease", "Chapter 8"],
      },
      {
        questionText: "Cell mediated immunity is mainly due to:",
        options: makeOptions("T lymphocytes", "B lymphocytes", "Neutrophils", "Erythrocytes"),
        correctAnswer: "A",
        solutionDetail: "T lymphocytes mediate cell mediated immunity.",
        solutionSteps: ["Recall immune cell roles."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Human Health and Disease", "Chapter 8"],
      },
      {
        questionText: "Vaccination provides:",
        options: makeOptions("Active acquired immunity", "Passive immunity", "Innate immunity", "No immunity"),
        correctAnswer: "A",
        solutionDetail: "Vaccines stimulate immune response and memory cells.",
        solutionSteps: ["Recall types of immunity."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Human Health and Disease", "Chapter 8"],
      },
      {
        questionText: "HIV primarily attacks:",
        options: makeOptions("Helper T cells (CD4)", "RBCs", "Platelets", "Neutrophils"),
        correctAnswer: "A",
        solutionDetail: "HIV targets CD4 helper T cells, weakening immunity.",
        solutionSteps: ["Recall HIV target cells."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Human Health and Disease", "Chapter 8"],
        pyqYear: 2017,
      },
      {
        questionText: "Interferons are produced by:",
        options: makeOptions("Virus infected cells", "Bacteria", "RBCs", "Platelets"),
        correctAnswer: "A",
        solutionDetail: "Interferons are released by virus infected cells to protect others.",
        solutionSteps: ["Recall role of interferons."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Human Health and Disease", "Chapter 8"],
      },
      {
        questionText: "Allergy is mediated by:",
        options: makeOptions("IgE antibodies and histamine", "IgG antibodies", "T cells only", "Complement only"),
        correctAnswer: "A",
        solutionDetail: "IgE mediated release of histamine causes allergies.",
        solutionSteps: ["Recall allergy mechanism."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Human Health and Disease", "Chapter 8"],
      },
      {
        questionText: "Cancer cells show:",
        options: makeOptions(
          "Uncontrolled proliferation and loss of contact inhibition",
          "No division",
          "Reduced metabolism",
          "Only apoptosis"
        ),
        correctAnswer: "A",
        solutionDetail: "Cancer cells divide uncontrollably and lose contact inhibition.",
        solutionSteps: ["Recall characteristics of cancer cells."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Human Health and Disease", "Chapter 8"],
      },
      {
        questionText: "An autoimmune disorder example is:",
        options: makeOptions("Rheumatoid arthritis", "Malaria", "Typhoid", "Tuberculosis"),
        correctAnswer: "A",
        solutionDetail: "Rheumatoid arthritis is an autoimmune disorder.",
        solutionSteps: ["Recall examples of autoimmune disorders."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Human Health and Disease", "Chapter 8"],
        pyqYear: 2021,
      },
    ],
  },
  {
    chapterNumber: 9,
    topicName: "Strategies for Enhancement in Food Production",
    questions: [
      {
        questionText: "Inbreeding depression occurs due to:",
        options: makeOptions(
          "Increased homozygosity of deleterious recessive alleles",
          "Increased heterozygosity",
          "Hybrid vigor",
          "Gene flow"
        ),
        correctAnswer: "A",
        solutionDetail: "Inbreeding increases homozygosity of harmful recessives.",
        solutionSteps: ["Recall cause of inbreeding depression."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Strategies for Enhancement in Food Production", "Chapter 9"],
      },
      {
        questionText: "Crossbreeding is:",
        options: makeOptions(
          "Mating between different breeds of the same species",
          "Mating within the same breed",
          "Cloning",
          "Hybridization between species"
        ),
        correctAnswer: "A",
        solutionDetail: "Crossbreeding involves different breeds of the same species.",
        solutionSteps: ["Recall definition of crossbreeding."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Strategies for Enhancement in Food Production", "Chapter 9"],
      },
      {
        questionText: "Outcrossing is mating of:",
        options: makeOptions(
          "Unrelated individuals of the same breed",
          "Related individuals of same breed",
          "Different species",
          "Male and female gametes outside body"
        ),
        correctAnswer: "A",
        solutionDetail: "Outcrossing uses unrelated individuals of the same breed.",
        solutionSteps: ["Recall meaning of outcrossing."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Strategies for Enhancement in Food Production", "Chapter 9"],
      },
      {
        questionText: "MOET stands for:",
        options: makeOptions(
          "Multiple Ovulation Embryo Transfer",
          "Maximum Ovulation Embryo Treatment",
          "Multiple Oocyte Extraction Technique",
          "Modern Ovulation Engineering Technique"
        ),
        correctAnswer: "A",
        solutionDetail: "MOET is Multiple Ovulation and Embryo Transfer.",
        solutionSteps: ["Recall the full form of MOET."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Strategies for Enhancement in Food Production", "Chapter 9"],
        pyqYear: 2018,
      },
      {
        questionText: "Apiculture refers to rearing of:",
        options: makeOptions("Honeybees", "Fish", "Silkworm", "Poultry"),
        correctAnswer: "A",
        solutionDetail: "Apiculture is beekeeping for honey production.",
        solutionSteps: ["Recall term for beekeeping."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Strategies for Enhancement in Food Production", "Chapter 9"],
      },
      {
        questionText: "Biofertilizer used for legumes is:",
        options: makeOptions("Rhizobium", "Nitrosomonas", "Azotobacter", "Spirulina"),
        correctAnswer: "A",
        solutionDetail: "Rhizobium fixes nitrogen in legume root nodules.",
        solutionSteps: ["Recall nitrogen fixing biofertilizers."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Strategies for Enhancement in Food Production", "Chapter 9"],
      },
      {
        questionText: "Micropropagation in tissue culture produces:",
        options: makeOptions("Clones", "Hybrids only", "Polyploids only", "Mutants only"),
        correctAnswer: "A",
        solutionDetail: "Tissue culture produces genetically identical clones.",
        solutionSteps: ["Recall outcome of tissue culture."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Strategies for Enhancement in Food Production", "Chapter 9"],
      },
      {
        questionText: "Artificial insemination in cattle is used to:",
        options: makeOptions(
          "Improve genetic quality of livestock",
          "Increase disease incidence",
          "Reduce milk yield",
          "Prevent fertilization"
        ),
        correctAnswer: "A",
        solutionDetail: "Artificial insemination helps improve livestock genetics.",
        solutionSteps: ["Recall applications of artificial insemination."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Strategies for Enhancement in Food Production", "Chapter 9"],
      },
    ],
  },
  {
    chapterNumber: 10,
    topicName: "Microbes in Human Welfare",
    questions: [
      {
        questionText: "Biogas is produced by:",
        options: makeOptions("Methanogens", "Rhizobium", "Nitrosomonas", "Lactobacillus"),
        correctAnswer: "A",
        solutionDetail: "Methanogens produce methane during anaerobic digestion.",
        solutionSteps: ["Recall organisms producing biogas."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Microbes in Human Welfare", "Chapter 10"],
      },
      {
        questionText: "Statins are produced by:",
        options: makeOptions("Monascus purpureus", "Penicillium", "Rhizobium", "E. coli"),
        correctAnswer: "A",
        solutionDetail: "Monascus purpureus produces statins that lower cholesterol.",
        solutionSteps: ["Recall microbe producing statins."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Microbes in Human Welfare", "Chapter 10"],
        pyqYear: 2019,
      },
      {
        questionText: "Streptokinase is used as:",
        options: makeOptions("Clot buster", "Antipyretic", "Antacid", "Analgesic"),
        correctAnswer: "A",
        solutionDetail: "Streptokinase dissolves blood clots.",
        solutionSteps: ["Recall therapeutic use of streptokinase."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Microbes in Human Welfare", "Chapter 10"],
      },
      {
        questionText: "Trichoderma is used as:",
        options: makeOptions("Biocontrol agent", "Biofertilizer", "Pathogen", "Antibiotic"),
        correctAnswer: "A",
        solutionDetail: "Trichoderma is a biocontrol fungus against plant pathogens.",
        solutionSteps: ["Recall biocontrol examples."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Microbes in Human Welfare", "Chapter 10"],
      },
      {
        questionText: "Activated sludge contains:",
        options: makeOptions("Flocs of bacteria and fungi", "Only algae", "Only protozoa", "Pure enzymes"),
        correctAnswer: "A",
        solutionDetail: "Activated sludge is rich in bacterial and fungal flocs.",
        solutionSteps: ["Recall features of activated sludge."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Microbes in Human Welfare", "Chapter 10"],
      },
      {
        questionText: "Microbe used in bread and beer making is:",
        options: makeOptions("Saccharomyces cerevisiae", "Rhizobium", "Nitrobacter", "Azotobacter"),
        correctAnswer: "A",
        solutionDetail: "Yeast Saccharomyces cerevisiae is used in fermentation.",
        solutionSteps: ["Recall yeast used in fermentation."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Microbes in Human Welfare", "Chapter 10"],
      },
      {
        questionText: "Bacillus thuringiensis produces:",
        options: makeOptions("Bt toxin", "Insulin", "Penicillin", "Vitamin B12"),
        correctAnswer: "A",
        solutionDetail: "Bacillus thuringiensis produces insecticidal Bt toxin.",
        solutionSteps: ["Recall Bt toxin source."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Microbes in Human Welfare", "Chapter 10"],
      },
      {
        questionText: "Secondary sewage treatment is also called:",
        options: makeOptions("Biological treatment", "Physical treatment", "Chemical treatment", "Mechanical treatment"),
        correctAnswer: "A",
        solutionDetail: "Secondary treatment relies on biological activity of microbes.",
        solutionSteps: ["Recall stages of sewage treatment."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Microbes in Human Welfare", "Chapter 10"],
      },
    ],
  },
  {
    chapterNumber: 11,
    topicName: "Biotechnology: Principles and Processes",
    questions: [
      {
        questionText: "Restriction endonucleases recognize:",
        options: makeOptions("Palindromic sequences", "Random sequences", "Only promoter regions", "Only introns"),
        correctAnswer: "A",
        solutionDetail: "Restriction enzymes cut at specific palindromic sequences.",
        solutionSteps: ["Recall restriction enzyme specificity."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biotechnology: Principles and Processes", "Chapter 11"],
      },
      {
        questionText: "Plasmids are used as vectors because they:",
        options: makeOptions(
          "Replicate independently in host cells",
          "Cannot carry foreign DNA",
          "Are always linear",
          "Lack selectable markers"
        ),
        correctAnswer: "A",
        solutionDetail: "Plasmids have origin of replication and can carry foreign DNA.",
        solutionSteps: ["Recall features of cloning vectors."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Biotechnology: Principles and Processes", "Chapter 11"],
      },
      {
        questionText: "Selectable marker genes help in:",
        options: makeOptions("Identifying transformants", "Cutting DNA", "Joining DNA fragments", "Translation"),
        correctAnswer: "A",
        solutionDetail: "Markers like antibiotic resistance identify transformed cells.",
        solutionSteps: ["Recall role of selectable markers."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biotechnology: Principles and Processes", "Chapter 11"],
      },
      {
        questionText: "During gel electrophoresis, DNA moves towards the:",
        options: makeOptions("Anode (positive)", "Cathode (negative)", "Center", "Random direction"),
        correctAnswer: "A",
        solutionDetail: "DNA is negatively charged and moves toward the anode.",
        solutionSteps: ["Recall movement of DNA in electric field."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biotechnology: Principles and Processes", "Chapter 11"],
      },
      {
        questionText: "PCR involves the steps:",
        options: makeOptions(
          "Denaturation, annealing, extension",
          "Replication, transcription, translation",
          "Ligase, helicase, primase",
          "Hybridization, digestion, ligation"
        ),
        correctAnswer: "A",
        solutionDetail: "PCR cycles through denaturation, annealing, and extension.",
        solutionSteps: ["Recall PCR cycle steps."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Biotechnology: Principles and Processes", "Chapter 11"],
        pyqYear: 2018,
      },
      {
        questionText: "Taq polymerase is obtained from:",
        options: makeOptions("Thermus aquaticus", "E. coli", "Bacillus subtilis", "Yeast"),
        correctAnswer: "A",
        solutionDetail: "Taq polymerase comes from the thermophilic bacterium Thermus aquaticus.",
        solutionSteps: ["Recall PCR enzyme source."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Biotechnology: Principles and Processes", "Chapter 11"],
        pyqYear: 2019,
      },
      {
        questionText: "Bioreactors provide:",
        options: makeOptions(
          "Large scale growth with controlled conditions",
          "Only storage of DNA",
          "Only DNA cutting",
          "Only protein separation"
        ),
        correctAnswer: "A",
        solutionDetail: "Bioreactors maintain optimal conditions for microbial growth.",
        solutionSteps: ["Recall purpose of bioreactors."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biotechnology: Principles and Processes", "Chapter 11"],
      },
      {
        questionText: "cDNA synthesis uses:",
        options: makeOptions("Reverse transcriptase", "DNA ligase", "RNA polymerase", "Primase"),
        correctAnswer: "A",
        solutionDetail: "Reverse transcriptase converts mRNA into cDNA.",
        solutionSteps: ["Recall enzyme used in cDNA synthesis."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Biotechnology: Principles and Processes", "Chapter 11"],
      },
    ],
  },
  {
    chapterNumber: 12,
    topicName: "Biotechnology and Its Applications",
    questions: [
      {
        questionText: "Bt toxin becomes active in the:",
        options: makeOptions("Alkaline gut of insects", "Acidic human stomach", "Plant cell vacuole", "Soil"),
        correctAnswer: "A",
        solutionDetail: "Bt protoxin is activated in the alkaline gut of insects.",
        solutionSteps: ["Recall activation of Bt toxin."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Biotechnology and Its Applications", "Chapter 12"],
      },
      {
        questionText: "RNA interference is used to:",
        options: makeOptions("Silence specific mRNA", "Increase DNA replication", "Translate proteins faster", "Create mutations"),
        correctAnswer: "A",
        solutionDetail: "RNAi silences specific mRNA to block gene expression.",
        solutionSteps: ["Recall purpose of RNA interference."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Biotechnology and Its Applications", "Chapter 12"],
      },
      {
        questionText: "Golden rice is enriched with:",
        options: makeOptions("Beta carotene", "Vitamin C", "Iron", "Protein"),
        correctAnswer: "A",
        solutionDetail: "Golden rice contains beta carotene, a vitamin A precursor.",
        solutionSteps: ["Recall feature of golden rice."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biotechnology and Its Applications", "Chapter 12"],
      },
      {
        questionText: "Gene therapy for ADA deficiency uses:",
        options: makeOptions(
          "Functional ADA gene inserted into lymphocytes",
          "Insulin injection",
          "Antibiotic treatment",
          "Vaccination"
        ),
        correctAnswer: "A",
        solutionDetail: "Functional ADA gene is introduced into lymphocytes for therapy.",
        solutionSteps: ["Recall ADA deficiency gene therapy."],
        difficultyLevel: 2,
        sourceType: "pyq",
        relatedTopics: ["Biotechnology and Its Applications", "Chapter 12"],
        pyqYear: 2017,
      },
      {
        questionText: "Bioremediation uses:",
        options: makeOptions(
          "Microbes to degrade pollutants",
          "Radiation therapy",
          "Chemical detergents only",
          "Physical removal only"
        ),
        correctAnswer: "A",
        solutionDetail: "Microbes degrade pollutants in bioremediation.",
        solutionSteps: ["Recall meaning of bioremediation."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biotechnology and Its Applications", "Chapter 12"],
      },
      {
        questionText: "Biopiracy refers to:",
        options: makeOptions(
          "Unauthorized use of biological resources",
          "Use of pesticides",
          "Selective breeding",
          "Random mutation"
        ),
        correctAnswer: "A",
        solutionDetail: "Biopiracy is unauthorized exploitation of bioresources.",
        solutionSteps: ["Recall the term biopiracy."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Biotechnology and Its Applications", "Chapter 12"],
      },
      {
        questionText: "Bt cotton cultivation reduces:",
        options: makeOptions("Use of chemical pesticides", "Yield of crop", "Fiber quality", "Soil fertility"),
        correctAnswer: "A",
        solutionDetail: "Bt cotton resists pests and reduces pesticide use.",
        solutionSteps: ["Recall advantage of Bt crops."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biotechnology and Its Applications", "Chapter 12"],
      },
      {
        questionText: "Transgenic animals are often used for:",
        options: makeOptions(
          "Producing therapeutic proteins",
          "Increasing soil fertility",
          "Making fertilizers",
          "Reducing pollution directly"
        ),
        correctAnswer: "A",
        solutionDetail: "Transgenic animals can produce therapeutic proteins in milk.",
        solutionSteps: ["Recall applications of transgenic animals."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Biotechnology and Its Applications", "Chapter 12"],
      },
    ],
  },
  {
    chapterNumber: 13,
    topicName: "Organisms and Populations",
    questions: [
      {
        questionText: "Population density can be measured as:",
        options: makeOptions(
          "Number, biomass, or percent cover",
          "Only number of individuals",
          "Only biomass",
          "Only percent cover"
        ),
        correctAnswer: "A",
        solutionDetail: "Population density can be expressed in multiple ways.",
        solutionSteps: ["Recall measures of population density."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Organisms and Populations", "Chapter 13"],
      },
      {
        questionText: "The exponential growth equation is:",
        options: makeOptions("dN/dt = rN", "dN/dt = rN(1-N/K)", "dN/dt = K - N", "dN/dt = rK"),
        correctAnswer: "A",
        solutionDetail: "Exponential growth is represented by dN/dt = rN.",
        solutionSteps: ["Recall exponential growth model."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Organisms and Populations", "Chapter 13"],
      },
      {
        questionText: "Carrying capacity of an environment is represented by:",
        options: makeOptions("K", "r", "N", "t"),
        correctAnswer: "A",
        solutionDetail: "K denotes carrying capacity in population growth models.",
        solutionSteps: ["Recall symbols in population equations."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Organisms and Populations", "Chapter 13"],
      },
      {
        questionText: "An age pyramid with a broad base indicates:",
        options: makeOptions("Expanding population", "Declining population", "Stable population", "Extinct population"),
        correctAnswer: "A",
        solutionDetail: "Broad base indicates more young individuals and growth.",
        solutionSteps: ["Recall age pyramid interpretations."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Organisms and Populations", "Chapter 13"],
      },
      {
        questionText: "r selected species show:",
        options: makeOptions(
          "Early maturity and high reproductive rate",
          "Late maturity and low reproductive rate",
          "Large body size and long life",
          "High parental care"
        ),
        correctAnswer: "A",
        solutionDetail: "r selected species reproduce rapidly with little parental care.",
        solutionSteps: ["Recall r and K selected traits."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Organisms and Populations", "Chapter 13"],
      },
      {
        questionText: "Commensalism example is:",
        options: makeOptions("Cattle egret and grazing cattle", "Lichen", "Tapeworm in human", "Lion and deer"),
        correctAnswer: "A",
        solutionDetail: "Cattle egret benefits while cattle are unaffected.",
        solutionSteps: ["Recall commensalism examples."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Organisms and Populations", "Chapter 13"],
      },
      {
        questionText: "Predation helps in:",
        options: makeOptions(
          "Controlling prey population and maintaining balance",
          "Eliminating all prey",
          "Preventing biodiversity",
          "Stopping evolution"
        ),
        correctAnswer: "A",
        solutionDetail: "Predation regulates prey numbers and maintains ecosystem balance.",
        solutionSteps: ["Recall ecological role of predation."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Organisms and Populations", "Chapter 13"],
      },
      {
        questionText: "Population growth is affected by:",
        options: makeOptions("Natality, mortality, immigration, emigration", "Only natality", "Only mortality", "Only emigration"),
        correctAnswer: "A",
        solutionDetail: "All four processes determine population growth.",
        solutionSteps: ["Recall factors affecting population size."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Organisms and Populations", "Chapter 13"],
      },
    ],
  },
  {
    chapterNumber: 14,
    topicName: "Ecosystem",
    questions: [
      {
        questionText: "Primary succession begins on:",
        options: makeOptions("Bare rock", "Forest soil", "Agricultural field", "Grassland"),
        correctAnswer: "A",
        solutionDetail: "Primary succession starts on bare rock or new land.",
        solutionSteps: ["Recall primary succession habitats."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Ecosystem", "Chapter 14"],
      },
      {
        questionText: "Detritus food chain starts with:",
        options: makeOptions("Dead organic matter", "Green plants", "Carnivores", "Herbivores"),
        correctAnswer: "A",
        solutionDetail: "Detritus food chain begins with dead organic matter.",
        solutionSteps: ["Recall detritus food chain."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Ecosystem", "Chapter 14"],
      },
      {
        questionText: "The 10 percent law refers to:",
        options: makeOptions(
          "Energy transfer between trophic levels",
          "Biomass production",
          "Population growth rate",
          "Water cycle"
        ),
        correctAnswer: "A",
        solutionDetail: "Only about 10 percent energy passes to next trophic level.",
        solutionSteps: ["Recall energy transfer rule."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Ecosystem", "Chapter 14"],
      },
      {
        questionText: "Standing crop refers to:",
        options: makeOptions(
          "Amount of living biomass at a given time",
          "Rate of photosynthesis",
          "Rate of respiration",
          "Number of species"
        ),
        correctAnswer: "A",
        solutionDetail: "Standing crop is biomass present at a specific time.",
        solutionSteps: ["Recall ecological terms."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Ecosystem", "Chapter 14"],
      },
      {
        questionText: "The phosphorus cycle lacks:",
        options: makeOptions("A gaseous phase", "Sedimentary phase", "Weathering phase", "Biological phase"),
        correctAnswer: "A",
        solutionDetail: "Phosphorus does not have a gaseous phase.",
        solutionSteps: ["Recall nutrient cycles."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Ecosystem", "Chapter 14"],
      },
      {
        questionText: "Pyramid of numbers can be inverted in:",
        options: makeOptions("Tree ecosystem", "Grassland ecosystem", "Pond ecosystem", "Desert ecosystem"),
        correctAnswer: "A",
        solutionDetail: "Few trees support many herbivores, inverting the pyramid.",
        solutionSteps: ["Recall pyramids of numbers."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Ecosystem", "Chapter 14"],
      },
      {
        questionText: "Decomposition involves:",
        options: makeOptions(
          "Fragmentation, leaching, catabolism, humification, mineralization",
          "Only fragmentation",
          "Only mineralization",
          "Only leaching"
        ),
        correctAnswer: "A",
        solutionDetail: "Decomposition proceeds through multiple steps.",
        solutionSteps: ["Recall steps of decomposition."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Ecosystem", "Chapter 14"],
      },
      {
        questionText: "Secondary succession occurs in:",
        options: makeOptions("Disturbed area with soil", "New lava rock", "Glacier retreat land", "Fresh sand dune"),
        correctAnswer: "A",
        solutionDetail: "Secondary succession begins where soil already exists.",
        solutionSteps: ["Recall secondary succession conditions."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Ecosystem", "Chapter 14"],
      },
      {
        questionText: "Ecological pyramids are always upright for:",
        options: makeOptions("Energy", "Numbers", "Biomass", "Population size"),
        correctAnswer: "A",
        solutionDetail: "Energy pyramid is always upright due to energy loss.",
        solutionSteps: ["Recall pyramid of energy."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Ecosystem", "Chapter 14"],
      },
    ],
  },
  {
    chapterNumber: 15,
    topicName: "Biodiversity and Conservation",
    questions: [
      {
        questionText: "Levels of biodiversity include:",
        options: makeOptions(
          "Genetic, species, ecosystem",
          "Molecular, cellular, tissue",
          "Organismal, organ, tissue",
          "Chemical, physical, biological"
        ),
        correctAnswer: "A",
        solutionDetail: "Biodiversity has genetic, species, and ecosystem levels.",
        solutionSteps: ["Recall levels of biodiversity."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biodiversity and Conservation", "Chapter 15"],
      },
      {
        questionText: "Endemism refers to:",
        options: makeOptions(
          "Species restricted to a particular region",
          "Species found everywhere",
          "Species that are extinct",
          "Species found only in oceans"
        ),
        correctAnswer: "A",
        solutionDetail: "Endemic species are limited to a specific region.",
        solutionSteps: ["Recall meaning of endemism."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biodiversity and Conservation", "Chapter 15"],
      },
      {
        questionText: "In situ conservation includes:",
        options: makeOptions(
          "National parks and sanctuaries",
          "Seed banks and zoos",
          "Botanical gardens only",
          "Laboratory gene banks only"
        ),
        correctAnswer: "A",
        solutionDetail: "In situ conservation protects species in natural habitats.",
        solutionSteps: ["Recall conservation methods."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biodiversity and Conservation", "Chapter 15"],
      },
      {
        questionText: "Ex situ conservation includes:",
        options: makeOptions(
          "Seed banks and zoos",
          "National parks",
          "Wildlife sanctuaries",
          "Biosphere reserves"
        ),
        correctAnswer: "A",
        solutionDetail: "Ex situ conservation is done outside natural habitat.",
        solutionSteps: ["Recall ex situ examples."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biodiversity and Conservation", "Chapter 15"],
      },
      {
        questionText: "IUCN categories include:",
        options: makeOptions(
          "Vulnerable, endangered, critically endangered",
          "Safe, secure, stable",
          "Common, rare, usual",
          "Protected, unsafe, unlisted"
        ),
        correctAnswer: "A",
        solutionDetail: "IUCN uses categories like vulnerable and endangered.",
        solutionSteps: ["Recall IUCN categories."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Biodiversity and Conservation", "Chapter 15"],
      },
      {
        questionText: "HIPPO stands for:",
        options: makeOptions(
          "Habitat loss, invasive species, pollution, population, overexploitation",
          "High intensity photosynthesis, pollution, population, ozone",
          "Habitat increase, pollution, protection, overgrowth",
          "Human impact, protection, population, overuse"
        ),
        correctAnswer: "A",
        solutionDetail: "HIPPO lists main causes of biodiversity loss.",
        solutionSteps: ["Recall HIPPO acronym."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Biodiversity and Conservation", "Chapter 15"],
      },
      {
        questionText: "Sacred groves are:",
        options: makeOptions(
          "Community protected forest patches",
          "Commercial plantations",
          "Urban parks",
          "Agricultural fields"
        ),
        correctAnswer: "A",
        solutionDetail: "Sacred groves are protected by local communities.",
        solutionSteps: ["Recall conservation traditions."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Biodiversity and Conservation", "Chapter 15"],
      },
      {
        questionText: "India is considered a mega diverse country because:",
        options: makeOptions(
          "It has high species richness and endemism",
          "It has low biodiversity",
          "It has no endemics",
          "It has only desert ecosystems"
        ),
        correctAnswer: "A",
        solutionDetail: "High species richness and endemism make India mega diverse.",
        solutionSteps: ["Recall features of mega diverse countries."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Biodiversity and Conservation", "Chapter 15"],
      },
    ],
  },
  {
    chapterNumber: 16,
    topicName: "Environmental Issues",
    questions: [
      {
        questionText: "Greenhouse gases include:",
        options: makeOptions("CO2 and CH4", "O2 and N2", "H2 and He", "Ar and Ne"),
        correctAnswer: "A",
        solutionDetail: "CO2 and CH4 are major greenhouse gases.",
        solutionSteps: ["Recall greenhouse gases."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Environmental Issues", "Chapter 16"],
      },
      {
        questionText: "Montreal Protocol deals with:",
        options: makeOptions("Ozone depletion", "Biodiversity loss", "Water pollution", "Noise pollution"),
        correctAnswer: "A",
        solutionDetail: "Montreal Protocol aims to reduce ozone depleting substances.",
        solutionSteps: ["Recall environmental agreements."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Environmental Issues", "Chapter 16"],
      },
      {
        questionText: "Biomagnification refers to:",
        options: makeOptions(
          "Increase in concentration of pollutants along food chain",
          "Decrease in population size",
          "Increase in oxygen content",
          "Decrease in temperature"
        ),
        correctAnswer: "A",
        solutionDetail: "Pollutants accumulate at higher trophic levels.",
        solutionSteps: ["Recall biomagnification."],
        difficultyLevel: 2,
        sourceType: "ncert",
        relatedTopics: ["Environmental Issues", "Chapter 16"],
      },
      {
        questionText: "Acid rain is mainly due to emissions of:",
        options: makeOptions("SO2 and NOx", "CO2 and CH4", "O2 and N2", "H2 and He"),
        correctAnswer: "A",
        solutionDetail: "SO2 and NOx form acids in the atmosphere.",
        solutionSteps: ["Recall causes of acid rain."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Environmental Issues", "Chapter 16"],
      },
      {
        questionText: "BOD is a measure of:",
        options: makeOptions(
          "Organic pollution in water",
          "Water hardness",
          "Soil fertility",
          "Air pollution"
        ),
        correctAnswer: "A",
        solutionDetail: "BOD indicates organic matter load in water.",
        solutionSteps: ["Recall significance of BOD."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Environmental Issues", "Chapter 16"],
      },
      {
        questionText: "Fly ash from thermal power plants can be used in:",
        options: makeOptions("Bricks and cement", "Food additives", "Drinking water", "Medical injections"),
        correctAnswer: "A",
        solutionDetail: "Fly ash is used in building materials like bricks.",
        solutionSteps: ["Recall uses of fly ash."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Environmental Issues", "Chapter 16"],
      },
      {
        questionText: "The 3Rs of waste management are:",
        options: makeOptions("Reduce, reuse, recycle", "Remove, reduce, replace", "Reuse, recharge, recover", "Reduce, repeat, recover"),
        correctAnswer: "A",
        solutionDetail: "Reduce, reuse, recycle are core waste management steps.",
        solutionSteps: ["Recall waste management hierarchy."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Environmental Issues", "Chapter 16"],
      },
      {
        questionText: "Noise pollution is measured in:",
        options: makeOptions("Decibels", "Watts", "Joules", "Lux"),
        correctAnswer: "A",
        solutionDetail: "Noise levels are measured in decibels.",
        solutionSteps: ["Recall unit of sound intensity."],
        difficultyLevel: 1,
        sourceType: "ncert",
        relatedTopics: ["Environmental Issues", "Chapter 16"],
      },
    ],
  },
];

async function ensureTopicId(topicName: string, chapterNumber: number) {
  const existing = await db
    .select({ id: contentTopics.id })
    .from(contentTopics)
    .where(
      and(
        eq(contentTopics.subject, "Biology"),
        eq(contentTopics.classLevel, "12"),
        eq(contentTopics.topicName, topicName)
      )
    )
    .limit(1);

  if (existing.length > 0) {
    return existing[0].id;
  }

  const inserted = await db
    .insert(contentTopics)
    .values({
      subject: "Biology",
      classLevel: "12",
      topicName,
      ncertChapter: `Chapter ${chapterNumber}`,
      referenceBooks: ["NCERT Biology"],
    })
    .returning({ id: contentTopics.id });

  return inserted[0].id;
}

async function seedBiologyClass12QuestionsExtended() {
  console.log("Seeding Biology Class 12 additional practice questions...");
  const targetPerChapter = 10;

  for (const chapter of chapters) {
    const topicId = await ensureTopicId(chapter.topicName, chapter.chapterNumber);
    const countResult = await db
      .select({ count: sql<number>`count(*)` })
      .from(questions)
      .where(eq(questions.topicId, topicId));
    const existingCount = Number(countResult[0]?.count ?? 0);

    if (existingCount >= targetPerChapter) {
      console.log(`  Chapter ${chapter.chapterNumber}: already has ${existingCount} questions, skipping`);
      continue;
    }

    const remaining = Math.max(targetPerChapter - existingCount, 0);
    if (remaining > chapter.questions.length) {
      console.warn(
        `  Chapter ${chapter.chapterNumber}: only ${chapter.questions.length} extra questions available for ${remaining} slots`
      );
    }

    const payload = chapter.questions.slice(0, remaining).map((question) => ({
      topicId,
      questionText: question.questionText,
      options: question.options,
      correctAnswer: question.correctAnswer,
      solutionDetail: question.solutionDetail,
      solutionSteps: question.solutionSteps ?? [],
      difficultyLevel: question.difficultyLevel,
      sourceType: question.sourceType,
      relatedTopics: question.relatedTopics,
      pyqYear: question.pyqYear ?? null,
    }));

    if (payload.length === 0) {
      console.log(`  Chapter ${chapter.chapterNumber}: no new questions to insert`);
      continue;
    }

    await db.insert(questions).values(payload);
    console.log(`  Chapter ${chapter.chapterNumber}: inserted ${payload.length} questions`);
  }

  console.log("Biology Class 12 additional questions seeding completed!");
}

seedBiologyClass12QuestionsExtended().catch((error) => {
  console.error("Failed to seed Biology Class 12 questions:", error);
});
